/*
 * TreeModelTest.java
 *
 * Created on 24 March 2003, 15:24
 */

package com.argus.financials.tree;

import com.argus.financials.api.code.FinancialClassID;

/**
 * 
 * @author Valeri CHIBAEV (mailto:apollosoft.net.au@gmail.com)
 */

import com.argus.financials.code.FinancialClass;
import com.argus.financials.config.PropertySourceManager;
import com.argus.financials.table.FinancialTableModel2;

public class TreeModelTest extends javax.swing.JFrame {

    private FinancialTreeModel model;

    /** Creates new form TreeModelTest */
    public TreeModelTest(java.util.Map financials)
            throws com.argus.financials.api.ServiceException {
        initComponents();

        FinancialTreeStructure fts = new FinancialTreeStructure();
        fts.add(new FinancialClass());
        // fts.add( new FinancialType() );
        // fts.add( new OwnerCode() );
        // fts.add( new CountryCode() );

        model = new FinancialTreeModel(financials);// { public void pack() {}
                                                    // };
        model.setStructure(fts);
        model.setRules(null);
        model.setFilters(null);
        model.build();

        jTree1.setModel(model);
        jTable1.setModel(new FinancialTableModel2(model));

        // jTree1.putClientProperty("JTree.lineStyle", "Horizontal");
        jTree1.putClientProperty("JTree.lineStyle", "Angled");

        // DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();
        // renderer.setLeafIcon(new ImageIcon("client/Image/History16.gif"));
        // jTree1.setCellRenderer(renderer);

        // System.out.println( "RowCount=" + model.getRowCount() );
        // for ( int i = 0; i < 30; i++ ) {
        // FinancialTreeModel.INode node = model.getRowAt( i );
        // System.out.println( "" + i + ").\t" + node + ", " + node.getLevel()
        // );
        // }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        jTree1.setRootVisible(false);
        jScrollPane1.setViewportView(jTree1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
                javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);

        jButton11.setText("jButton1");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton11ActionPerformed

    }// GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        FinancialTreeFilter objectTypeFilter = new FinancialTreeFilter(
                new FinancialClass());
        objectTypeFilter.add(FinancialClassID.RC_ASSET_CASH);
        objectTypeFilter.add(FinancialClassID.RC_ASSET_INVESTMENT);

        // FinancialTreeFilter ownerFilter = new FinancialTreeFilter( new
        // OwnerCode() );
        // ownerFilter.add( OwnerCode.JOINT );
        // ownerFilter.add( OwnerCode.PARTNER );

        FinancialTreeFilters filters = new FinancialTreeFilters();
        filters.add(objectTypeFilter);
        // filters.add( ownerFilter );

        model.setFilters(filters);

        FinancialTreeModel model2 = model.buildCopy();

        jTree1.setModel(model2);
        jTable1.setModel(new com.argus.financials.table.FinancialTableModel2(
                model2));

    }// GEN-LAST:event_jButton1ActionPerformed

    /** Exit the Application */
    /**
     * @param args
     *            the command line arguments
     */
    static void main(String args[]) throws com.argus.financials.api.ServiceException {
        try {
            PropertySourceManager.getInstance().load("force.properties");
        } catch (Exception e) {
            e.printStackTrace(System.err);
            PropertySourceManager.getInstance().unload();
            System.exit(1);
        }

        java.util.Map financials = new java.util.HashMap(); // RmiParams.getInstance().getClientPerson().getFinancials()

        TreeModelTest view = new TreeModelTest(financials);
        view.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                PropertySourceManager.getInstance().unload();
                System.exit(0);
            }
        });

        view.show();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree jTree1;

    private javax.swing.JTable jTable1;

    private javax.swing.JButton jButton2;

    private javax.swing.JButton jButton1;

    private javax.swing.JButton jButton11;

    private javax.swing.JScrollPane jScrollPane2;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
