/*
 * ListSelection.java
 *
 * Created on 19 March 2002, 17:31
 */

package com.argus.financials.ui;

import java.util.Vector;

import javax.swing.JList;

import com.argus.financials.swing.SwingUtil;

/**
 * 
 * @author valeri chibaev
 */

public class ListSelection extends javax.swing.JPanel {

    public static final int CANCEL_OPTION = javax.swing.JOptionPane.CANCEL_OPTION;

    public static final int OK_OPTION = javax.swing.JOptionPane.OK_OPTION;

    private JList list;

    private int result; // CANCEL_OPTION, OK_OPTION

    /** Creates new form ListSelection */
    public ListSelection(final JList list) {
        initComponents();

        this.list = list;
        jScrollPane.setViewportView(list);

        // *
        this.list
                .addListSelectionListener(new javax.swing.event.ListSelectionListener() {
                    public void valueChanged(
                            javax.swing.event.ListSelectionEvent evt) {

                        if (evt.getValueIsAdjusting())
                            return;

                        jButtonOK.setEnabled(ListSelection.this.list
                                .getSelectedIndex() >= 0);

                        // ListSelection.this.list.setToolTipText(
                        // evt.toString() );
                        // jScrollPane.setToolTipText( evt.toString() );

                        repaint();

                    }

                }

                );
        // */

        if (this.list instanceof CheckBoxList) {
            this.list.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent e) {

                    doSelectAll(e);
                }
            });
        } else {
            this.list.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (evt.getClickCount() == 2) {
                        SwingUtil.setVisible(ListSelection.this, false);
                        result = OK_OPTION;
                    }
                }
            });

        }

        result = CANCEL_OPTION;
    }

    public void doSelectAll(java.awt.event.KeyEvent e) {
        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_A) {
            ((CheckBoxList) list).selectAll(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jScrollPane = new javax.swing.JScrollPane();
        jPanelControls = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setPreferredSize(new java.awt.Dimension(300, 200));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane.setPreferredSize(new java.awt.Dimension(10, 1000));
        add(jScrollPane);

        jPanelControls.setBorder(new javax.swing.border.EtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanelControls.add(jPanel1);

        jButtonOK.setText("OK");
        jButtonOK.setEnabled(false);
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanel2.add(jButtonOK);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel2.add(jButtonCancel);

        jPanelControls.add(jPanel2);

        add(jPanelControls);

    }// GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        result = CANCEL_OPTION;
    }// GEN-LAST:event_formComponentShown

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOKActionPerformed
        SwingUtil.setVisible(this, false);
        result = OK_OPTION;
    }// GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
        SwingUtil.setVisible(this, false);
        // result = CANCEL_OPTION; // by default
    }// GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;

    private javax.swing.JPanel jPanelControls;

    private javax.swing.JScrollPane jScrollPane;

    private javax.swing.JButton jButtonOK;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel1;

    // End of variables declaration//GEN-END:variables

    public int getResult() {
        return result;
    }

    public boolean isEmpty() {
        return list.isSelectionEmpty();
    }

    public void setListData(Object[] listData) {
        list.setListData(listData);
    }

    public void setListData(Vector listData) {
        list.setListData(listData);
    }

    public void setSingleSelection() {
        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public void setMultipleSelection() {
        list
                .setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    public void setSingleIntervalSelection() {
        list
                .setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    public Object getSelectedValue() {
        return list.getSelectedValue();
    }

    public Object[] getSelectedValues() {
        return list.getSelectedValues();
    }

    public void setSelectedValue(Object anObject, boolean shouldScroll) {
        list.setSelectedValue(anObject, shouldScroll);
    }

}
