/*
 * PlanTracker.java
 *
 * Created on 3 September 2001, 09:37
 */

package com.argus.financials.ui;

/**
 * 
 * @author valeri chibaev
 * @version
 */

import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.Font;

import javax.swing.JComponent;

import com.argus.financials.code.InvalidCodeException;
import com.argus.financials.service.PersonService;
import com.argus.swing.SwingUtils;

public final class PlanTracker extends javax.swing.JPanel {

    private static PlanTracker view;

    public static Cursor handCursor = new Cursor(Cursor.HAND_CURSOR);

    // public static javax.swing.border.Border softBevelBorder = new
    // javax.swing.border.SoftBevelBorder(0);
    private Font defaultFont;

    private Font highlightFont;

    private CardLayout cardLayout;

    public static PlanTracker getInstance() {

        if (view == null)
            view = new PlanTracker();

        return view;

    }

    /** Creates new form PlanTracker */
    private PlanTracker() {
        initComponents();

        // pack();

        // SwingUtils.setDefaultFont(this);

        defaultFont = SwingUtils.getDefaultFont();
        highlightFont = new Font(defaultFont.getFontName(), Font.BOLD,
                defaultFont.getSize());

        cardLayout = (CardLayout) (this.getLayout());

    }

    public String getViewCaption() {
        return "Plan Tracker";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jPanelMain = new javax.swing.JPanel();
        jCheckBoxClientDetails = new javax.swing.JCheckBox();
        jLabelClientDetails = new javax.swing.JLabel();
        jCheckBoxPartnerDetails = new javax.swing.JCheckBox();
        jLabelPartnerDetails = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabelFinancialPosition = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabelGoalsObjectives = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabelRiskEvaluation = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabelStrategySelection = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabelWritePlan = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jPanelClientDetails = new javax.swing.JPanel();
        jLabelDependents = new javax.swing.JLabel();
        jLabelContactDetails = new javax.swing.JLabel();
        jLabelProfessionalContacts = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jLabelClientDetails2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jPanelPartnerDetails = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jCheckBox17 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanelFinancialDetails = new javax.swing.JPanel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox23 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanelGoalsObjectives = new javax.swing.JPanel();
        jCheckBox24 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox25 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jCheckBox26 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox27 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanelRiskEvaluations = new javax.swing.JPanel();
        jCheckBox28 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanelStrategySelection = new javax.swing.JPanel();
        jCheckBox30 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jCheckBox31 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jCheckBox32 = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanelWritePlan = new javax.swing.JPanel();
        jCheckBox33 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jCheckBox34 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jCheckBox35 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        jCheckBox36 = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        setMinimumSize(new java.awt.Dimension(100, 200));
        setPreferredSize(new java.awt.Dimension(180, 300));
        jPanelMain.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;

        jCheckBoxClientDetails.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBoxClientDetails, gridBagConstraints1);

        jLabelClientDetails.setText("Client Details");
        jLabelClientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseClicked(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 0;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabelClientDetails, gridBagConstraints1);

        jCheckBoxPartnerDetails.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBoxPartnerDetails, gridBagConstraints1);

        jLabelPartnerDetails.setText("Partner Details");
        jLabelPartnerDetails
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelPartnerDetailsMouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabelPartnerDetails, gridBagConstraints1);

        jCheckBox3.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBox3, gridBagConstraints1);

        jLabelFinancialPosition.setText("Financial Position");
        jLabelFinancialPosition
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelFinancialPositionMouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabelFinancialPosition, gridBagConstraints1);

        jCheckBox4.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBox4, gridBagConstraints1);

        jLabelGoalsObjectives.setText("Goals & Objectives");
        jLabelGoalsObjectives
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelGoalsObjectivesMouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabelGoalsObjectives, gridBagConstraints1);

        jCheckBox5.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBox5, gridBagConstraints1);

        jLabelRiskEvaluation.setText("Risk Evaluation/ISO");
        jLabelRiskEvaluation
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelRiskEvaluationMouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabelRiskEvaluation, gridBagConstraints1);

        jCheckBox6.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBox6, gridBagConstraints1);

        jLabelStrategySelection.setText("Strategy Selection");
        jLabelStrategySelection
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelStrategySelectionMouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabelStrategySelection, gridBagConstraints1);

        jCheckBox7.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBox7, gridBagConstraints1);

        jLabelWritePlan.setText("Write Plan");
        jLabelWritePlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelWritePlanMouseClicked(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabelWritePlan, gridBagConstraints1);

        jCheckBox8.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanelMain.add(jCheckBox8, gridBagConstraints1);

        jLabel8.setText("Client Plan Complete!");
        jLabel8.setEnabled(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints1.ipadx = 20;
        gridBagConstraints1.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelMain.add(jLabel8, gridBagConstraints1);

        add(jPanelMain, "jPanelMain");

        jPanelClientDetails.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;

        jLabelDependents.setText("Dependents");
        jLabelDependents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDependentsMouseClicked(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 6;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails.add(jLabelDependents, gridBagConstraints2);

        jLabelContactDetails.setText("Contact Details");
        jLabelContactDetails
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelContactDetailsMouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails.add(jLabelContactDetails, gridBagConstraints2);

        jLabelProfessionalContacts.setText("Professional Contacts");
        jLabelProfessionalContacts
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelProfessionalContactsMouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 4;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails
                .add(jLabelProfessionalContacts, gridBagConstraints2);

        jCheckBox10.setEnabled(false);
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails.add(jCheckBox10, gridBagConstraints2);

        jCheckBox12.setEnabled(false);
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 4;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails.add(jCheckBox12, gridBagConstraints2);

        jCheckBox14.setEnabled(false);
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 6;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails.add(jCheckBox14, gridBagConstraints2);

        jCheckBox15.setEnabled(false);
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails.add(jCheckBox15, gridBagConstraints2);

        jLabelClientDetails2.setText("Clilent Details");
        jLabelClientDetails2
                .addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabelClientDetails2MouseClicked(evt);
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseExited(evt);
                    }

                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        jLabelClientDetailsMouseEntered(evt);
                    }
                });

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 0;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints2.insets = new java.awt.Insets(4, 0, 4, 0);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelClientDetails.add(jLabelClientDetails2, gridBagConstraints2);

        jButtonBack.setText("Back");
        jButtonBack.setPreferredSize(new java.awt.Dimension(70, 27));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel3.add(jButtonBack);

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 7;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
        jPanelClientDetails.add(jPanel3, gridBagConstraints2);

        add(jPanelClientDetails, "jPanelClientDetails");

        jPanelPartnerDetails.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints3;

        jLabel16.setText("Partner Details");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 0;
        gridBagConstraints3.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPartnerDetails.add(jLabel16, gridBagConstraints3);

        jCheckBox17.setEnabled(false);
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 2;
        gridBagConstraints3.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPartnerDetails.add(jCheckBox17, gridBagConstraints3);

        jLabel18.setText("Contact Details");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 2;
        gridBagConstraints3.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPartnerDetails.add(jLabel18, gridBagConstraints3);

        jCheckBox19.setEnabled(false);
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 0;
        jPanelPartnerDetails.add(jCheckBox19, gridBagConstraints3);

        jButton2.setText("Back");
        jButton2.setPreferredSize(new java.awt.Dimension(70, 27));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel5.add(jButton2);

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 4;
        gridBagConstraints3.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.fill = java.awt.GridBagConstraints.BOTH;
        jPanelPartnerDetails.add(jPanel5, gridBagConstraints3);

        add(jPanelPartnerDetails, "jPanelPartnerDetails");

        jPanelFinancialDetails.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints4;

        jCheckBox21.setEnabled(false);
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 1;
        gridBagConstraints4.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelFinancialDetails.add(jCheckBox21, gridBagConstraints4);

        jLabel21.setText("Assets & Liabilities");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 1;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints4.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelFinancialDetails.add(jLabel21, gridBagConstraints4);

        jCheckBox22.setEnabled(false);
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 2;
        gridBagConstraints4.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelFinancialDetails.add(jCheckBox22, gridBagConstraints4);

        jLabel22.setText("Income & Expenditure");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 2;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints4.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelFinancialDetails.add(jLabel22, gridBagConstraints4);

        jCheckBox23.setEnabled(false);
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 3;
        gridBagConstraints4.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelFinancialDetails.add(jCheckBox23, gridBagConstraints4);

        jLabel23.setText("Insurance");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseExited(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClientDetailsMouseEntered(evt);
            }
        });

        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 3;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints4.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelFinancialDetails.add(jLabel23, gridBagConstraints4);

        jButton3.setText("Back");
        jButton3.setPreferredSize(new java.awt.Dimension(70, 27));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel7.add(jButton3);

        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 4;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.BOTH;
        jPanelFinancialDetails.add(jPanel7, gridBagConstraints4);

        add(jPanelFinancialDetails, "jPanelFinancialDetails");

        jPanelGoalsObjectives.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints5;

        jCheckBox24.setEnabled(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 0;
        gridBagConstraints5.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jCheckBox24, gridBagConstraints5);

        jLabel24.setText("Goals & Objectives");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 0;
        gridBagConstraints5.insets = new java.awt.Insets(4, 0, 4, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jLabel24, gridBagConstraints5);

        jCheckBox25.setEnabled(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 1;
        gridBagConstraints5.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jCheckBox25, gridBagConstraints5);

        jLabel25.setText("Short Term Goals");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 1;
        gridBagConstraints5.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jLabel25, gridBagConstraints5);

        jCheckBox26.setEnabled(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 2;
        gridBagConstraints5.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jCheckBox26, gridBagConstraints5);

        jLabel26.setText("Long Term Goals");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 2;
        gridBagConstraints5.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jLabel26, gridBagConstraints5);

        jCheckBox27.setEnabled(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 3;
        gridBagConstraints5.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jCheckBox27, gridBagConstraints5);

        jLabel27.setText("Objectives");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 3;
        gridBagConstraints5.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelGoalsObjectives.add(jLabel27, gridBagConstraints5);

        jButton4.setText("Back");
        jButton4.setPreferredSize(new java.awt.Dimension(70, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel9.add(jButton4);

        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 4;
        gridBagConstraints5.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.fill = java.awt.GridBagConstraints.BOTH;
        jPanelGoalsObjectives.add(jPanel9, gridBagConstraints5);

        add(jPanelGoalsObjectives, "jPanelGoalsObjectives");

        jPanelRiskEvaluations.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints6;

        jCheckBox28.setEnabled(false);
        gridBagConstraints6 = new java.awt.GridBagConstraints();
        gridBagConstraints6.gridx = 0;
        gridBagConstraints6.gridy = 0;
        gridBagConstraints6.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints6.anchor = java.awt.GridBagConstraints.WEST;
        jPanelRiskEvaluations.add(jCheckBox28, gridBagConstraints6);

        jLabel28.setText("Risk Evaluation/ISO");
        gridBagConstraints6 = new java.awt.GridBagConstraints();
        gridBagConstraints6.gridx = 1;
        gridBagConstraints6.gridy = 0;
        gridBagConstraints6.insets = new java.awt.Insets(10, 0, 10, 0);
        gridBagConstraints6.anchor = java.awt.GridBagConstraints.WEST;
        jPanelRiskEvaluations.add(jLabel28, gridBagConstraints6);

        jCheckBox29.setEnabled(false);
        gridBagConstraints6 = new java.awt.GridBagConstraints();
        gridBagConstraints6.gridx = 0;
        gridBagConstraints6.gridy = 1;
        gridBagConstraints6.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints6.anchor = java.awt.GridBagConstraints.WEST;
        jPanelRiskEvaluations.add(jCheckBox29, gridBagConstraints6);

        jLabel29.setText("Questionnarie");
        gridBagConstraints6 = new java.awt.GridBagConstraints();
        gridBagConstraints6.gridx = 1;
        gridBagConstraints6.gridy = 1;
        gridBagConstraints6.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints6.anchor = java.awt.GridBagConstraints.WEST;
        jPanelRiskEvaluations.add(jLabel29, gridBagConstraints6);

        jButton5.setText("Back");
        jButton5.setPreferredSize(new java.awt.Dimension(70, 27));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel11.add(jButton5);

        gridBagConstraints6 = new java.awt.GridBagConstraints();
        gridBagConstraints6.gridx = 0;
        gridBagConstraints6.gridy = 4;
        gridBagConstraints6.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints6.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints6.fill = java.awt.GridBagConstraints.BOTH;
        jPanelRiskEvaluations.add(jPanel11, gridBagConstraints6);

        add(jPanelRiskEvaluations, "jPanelRiskEvaluations");

        jPanelStrategySelection.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints7;

        jCheckBox30.setEnabled(false);
        gridBagConstraints7 = new java.awt.GridBagConstraints();
        gridBagConstraints7.gridx = 0;
        gridBagConstraints7.gridy = 0;
        gridBagConstraints7.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints7.anchor = java.awt.GridBagConstraints.WEST;
        jPanelStrategySelection.add(jCheckBox30, gridBagConstraints7);

        jLabel30.setText("Strategy Selection");
        gridBagConstraints7 = new java.awt.GridBagConstraints();
        gridBagConstraints7.gridx = 1;
        gridBagConstraints7.gridy = 0;
        gridBagConstraints7.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints7.anchor = java.awt.GridBagConstraints.WEST;
        jPanelStrategySelection.add(jLabel30, gridBagConstraints7);

        jCheckBox31.setEnabled(false);
        gridBagConstraints7 = new java.awt.GridBagConstraints();
        gridBagConstraints7.gridx = 0;
        gridBagConstraints7.gridy = 1;
        gridBagConstraints7.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints7.anchor = java.awt.GridBagConstraints.WEST;
        jPanelStrategySelection.add(jCheckBox31, gridBagConstraints7);

        jLabel31.setText("Investment Guru");
        gridBagConstraints7 = new java.awt.GridBagConstraints();
        gridBagConstraints7.gridx = 1;
        gridBagConstraints7.gridy = 1;
        gridBagConstraints7.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints7.anchor = java.awt.GridBagConstraints.WEST;
        jPanelStrategySelection.add(jLabel31, gridBagConstraints7);

        jCheckBox32.setEnabled(false);
        gridBagConstraints7 = new java.awt.GridBagConstraints();
        gridBagConstraints7.gridx = 0;
        gridBagConstraints7.gridy = 2;
        gridBagConstraints7.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints7.anchor = java.awt.GridBagConstraints.WEST;
        jPanelStrategySelection.add(jCheckBox32, gridBagConstraints7);

        jLabel32.setText("Manual Selection");
        gridBagConstraints7 = new java.awt.GridBagConstraints();
        gridBagConstraints7.gridx = 1;
        gridBagConstraints7.gridy = 2;
        gridBagConstraints7.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints7.anchor = java.awt.GridBagConstraints.WEST;
        jPanelStrategySelection.add(jLabel32, gridBagConstraints7);

        jButton6.setText("Back");
        jButton6.setPreferredSize(new java.awt.Dimension(70, 27));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel13.add(jButton6);

        gridBagConstraints7 = new java.awt.GridBagConstraints();
        gridBagConstraints7.gridx = 0;
        gridBagConstraints7.gridy = 7;
        gridBagConstraints7.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints7.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints7.fill = java.awt.GridBagConstraints.BOTH;
        jPanelStrategySelection.add(jPanel13, gridBagConstraints7);

        add(jPanelStrategySelection, "jPanelStrategySelection");

        jPanelWritePlan.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints8;

        jCheckBox33.setEnabled(false);
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 0;
        gridBagConstraints8.gridy = 0;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jCheckBox33, gridBagConstraints8);

        jLabel33.setText("Write Plan");
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 1;
        gridBagConstraints8.gridy = 0;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jLabel33, gridBagConstraints8);

        jCheckBox34.setEnabled(false);
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 0;
        gridBagConstraints8.gridy = 1;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jCheckBox34, gridBagConstraints8);

        jLabel34.setText("No Advice");
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 1;
        gridBagConstraints8.gridy = 1;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jLabel34, gridBagConstraints8);

        jCheckBox35.setEnabled(false);
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 0;
        gridBagConstraints8.gridy = 2;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jCheckBox35, gridBagConstraints8);

        jLabel35.setText("Limited Advice");
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 1;
        gridBagConstraints8.gridy = 2;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jLabel35, gridBagConstraints8);

        jCheckBox36.setEnabled(false);
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 0;
        gridBagConstraints8.gridy = 3;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jCheckBox36, gridBagConstraints8);

        jLabel36.setText("Full Advice");
        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 1;
        gridBagConstraints8.gridy = 3;
        gridBagConstraints8.insets = new java.awt.Insets(5, 0, 5, 0);
        gridBagConstraints8.anchor = java.awt.GridBagConstraints.WEST;
        jPanelWritePlan.add(jLabel36, gridBagConstraints8);

        jButton7.setText("Back");
        jButton7.setPreferredSize(new java.awt.Dimension(70, 27));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel15.add(jButton7);

        gridBagConstraints8 = new java.awt.GridBagConstraints();
        gridBagConstraints8.gridx = 0;
        gridBagConstraints8.gridy = 4;
        gridBagConstraints8.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints8.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints8.fill = java.awt.GridBagConstraints.BOTH;
        jPanelWritePlan.add(jPanel15, gridBagConstraints8);

        add(jPanelWritePlan, "jPanelWritePlan");

    }// GEN-END:initComponents

    private void jLabelDependentsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelDependentsMouseClicked
        // MainFrame.getMainFrame().displayClient();
        ClientView.getClientView().setPage(ClientView.DEPENDENTS);
    }// GEN-LAST:event_jLabelDependentsMouseClicked

    private void jLabelProfessionalContactsMouseClicked(
            java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelProfessionalContactsMouseClicked
        // MainFrame.getMainFrame().displayClient();
        ClientView.getClientView().setPage(ClientView.PROFESSIONAL_CONTACTS);
    }// GEN-LAST:event_jLabelProfessionalContactsMouseClicked

    private void jLabelContactDetailsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelContactDetailsMouseClicked
        // MainFrame.getMainFrame().displayClient();
        ClientView.getClientView().setPage(ClientView.CONTACT_DETAILS);
    }// GEN-LAST:event_jLabelContactDetailsMouseClicked

    private void jLabelClientDetails2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelClientDetails2MouseClicked
        // MainFrame.getMainFrame().displayClient();
        ClientView.getClientView().setPage(ClientView.PERSONAL_DETAILS);
    }// GEN-LAST:event_jLabelClientDetails2MouseClicked

    private void jLabelWritePlanMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelWritePlanMouseClicked
        cardLayout.show(this, "jPanelWritePlan");
    }// GEN-LAST:event_jLabelWritePlanMouseClicked

    private void jLabelStrategySelectionMouseClicked(
            java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelStrategySelectionMouseClicked
        cardLayout.show(this, "jPanelStrategySelection");
    }// GEN-LAST:event_jLabelStrategySelectionMouseClicked

    private void jLabelRiskEvaluationMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelRiskEvaluationMouseClicked
        cardLayout.show(this, "jPanelRiskEvaluations");
    }// GEN-LAST:event_jLabelRiskEvaluationMouseClicked

    private void jLabelGoalsObjectivesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelGoalsObjectivesMouseClicked
        cardLayout.show(this, "jPanelGoalsObjectives");
    }// GEN-LAST:event_jLabelGoalsObjectivesMouseClicked

    private void jLabelFinancialPositionMouseClicked(
            java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelFinancialPositionMouseClicked
        cardLayout.show(this, "jPanelFinancialDetails");
    }// GEN-LAST:event_jLabelFinancialPositionMouseClicked

    private void jLabelPartnerDetailsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelPartnerDetailsMouseClicked
        cardLayout.show(this, "jPanelPartnerDetails");
    }// GEN-LAST:event_jLabelPartnerDetailsMouseClicked

    private void jLabelClientDetailsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelClientDetailsMouseClicked
        cardLayout.show(this, "jPanelClientDetails");
    }// GEN-LAST:event_jLabelClientDetailsMouseClicked

    private void jLabelClientDetailsMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelClientDetailsMouseExited
        JComponent c = (JComponent) evt.getSource();
        c.setCursor(Cursor.getDefaultCursor());
        // c.setBorder( null );
        c.setFont(defaultFont);
    }// GEN-LAST:event_jLabelClientDetailsMouseExited

    private void jLabelClientDetailsMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelClientDetailsMouseEntered
        JComponent c = (JComponent) evt.getSource();
        c.setCursor(handCursor);
        // c.setBorder( softBevelBorder );
        c.setFont(highlightFont);
    }// GEN-LAST:event_jLabelClientDetailsMouseEntered

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonBackActionPerformed
        cardLayout.first(this);
    }// GEN-LAST:event_jButtonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMain;

    private javax.swing.JCheckBox jCheckBoxClientDetails;

    private javax.swing.JLabel jLabelClientDetails;

    private javax.swing.JCheckBox jCheckBoxPartnerDetails;

    private javax.swing.JLabel jLabelPartnerDetails;

    private javax.swing.JCheckBox jCheckBox3;

    private javax.swing.JLabel jLabelFinancialPosition;

    private javax.swing.JCheckBox jCheckBox4;

    private javax.swing.JLabel jLabelGoalsObjectives;

    private javax.swing.JCheckBox jCheckBox5;

    private javax.swing.JLabel jLabelRiskEvaluation;

    private javax.swing.JCheckBox jCheckBox6;

    private javax.swing.JLabel jLabelStrategySelection;

    private javax.swing.JCheckBox jCheckBox7;

    private javax.swing.JLabel jLabelWritePlan;

    private javax.swing.JCheckBox jCheckBox8;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JPanel jPanelClientDetails;

    private javax.swing.JLabel jLabelDependents;

    private javax.swing.JLabel jLabelContactDetails;

    private javax.swing.JLabel jLabelProfessionalContacts;

    private javax.swing.JCheckBox jCheckBox10;

    private javax.swing.JCheckBox jCheckBox12;

    private javax.swing.JCheckBox jCheckBox14;

    private javax.swing.JCheckBox jCheckBox15;

    private javax.swing.JLabel jLabelClientDetails2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JButton jButtonBack;

    private javax.swing.JPanel jPanelPartnerDetails;

    private javax.swing.JLabel jLabel16;

    private javax.swing.JCheckBox jCheckBox17;

    private javax.swing.JLabel jLabel18;

    private javax.swing.JCheckBox jCheckBox19;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JButton jButton2;

    private javax.swing.JPanel jPanelFinancialDetails;

    private javax.swing.JCheckBox jCheckBox21;

    private javax.swing.JLabel jLabel21;

    private javax.swing.JCheckBox jCheckBox22;

    private javax.swing.JLabel jLabel22;

    private javax.swing.JCheckBox jCheckBox23;

    private javax.swing.JLabel jLabel23;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JButton jButton3;

    private javax.swing.JPanel jPanelGoalsObjectives;

    private javax.swing.JCheckBox jCheckBox24;

    private javax.swing.JLabel jLabel24;

    private javax.swing.JCheckBox jCheckBox25;

    private javax.swing.JLabel jLabel25;

    private javax.swing.JCheckBox jCheckBox26;

    private javax.swing.JLabel jLabel26;

    private javax.swing.JCheckBox jCheckBox27;

    private javax.swing.JLabel jLabel27;

    private javax.swing.JPanel jPanel9;

    private javax.swing.JButton jButton4;

    private javax.swing.JPanel jPanelRiskEvaluations;

    private javax.swing.JCheckBox jCheckBox28;

    private javax.swing.JLabel jLabel28;

    private javax.swing.JCheckBox jCheckBox29;

    private javax.swing.JLabel jLabel29;

    private javax.swing.JPanel jPanel11;

    private javax.swing.JButton jButton5;

    private javax.swing.JPanel jPanelStrategySelection;

    private javax.swing.JCheckBox jCheckBox30;

    private javax.swing.JLabel jLabel30;

    private javax.swing.JCheckBox jCheckBox31;

    private javax.swing.JLabel jLabel31;

    private javax.swing.JCheckBox jCheckBox32;

    private javax.swing.JLabel jLabel32;

    private javax.swing.JPanel jPanel13;

    private javax.swing.JButton jButton6;

    private javax.swing.JPanel jPanelWritePlan;

    private javax.swing.JCheckBox jCheckBox33;

    private javax.swing.JLabel jLabel33;

    private javax.swing.JCheckBox jCheckBox34;

    private javax.swing.JLabel jLabel34;

    private javax.swing.JCheckBox jCheckBox35;

    private javax.swing.JLabel jLabel35;

    private javax.swing.JCheckBox jCheckBox36;

    private javax.swing.JLabel jLabel36;

    private javax.swing.JPanel jPanel15;

    private javax.swing.JButton jButton7;

    // End of variables declaration//GEN-END:variables

    public void updateView(PersonService person) throws com.argus.financials.service.ServiceException {

    }

    public void saveView(PersonService person) throws com.argus.financials.service.ServiceException,
            InvalidCodeException {
    }

    public void clearView() {
    }

    public Object getObject() {
        return null;
    }

    public void setObject(Object value) {

    }

    public Integer getObjectType() {
        return null;
    }

}
