/*
 * KnownIncomeView.java
 *
 * Created on 6 August 2003, 11:01
 */

package com.argus.financials.ui;

/**
 *
 * @author  Valeri Shibaev
 */


//import com.argus.swing.NumberFormatter;
//import com.argus.swing.WindowFactory;

public class TemplateView extends BaseFinancialsView {
    
    public static void main( String [] args ) {
        main( args, new TemplateView() );
    }

    
    /** Creates new form KnownIncomeView */
    public TemplateView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.GridBagLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
