/*
 * ModelSelectionView.java
 *
 * Created on July 9, 2002, 5:07 PM
 */

package com.argus.financials.ui.strategy;

/**
 * 
 * @author valeri chibaev
 */

import java.util.Vector;

import com.argus.financials.code.FinancialType;
import com.argus.financials.service.PersonService;
import com.argus.financials.strategy.Strategy;
import com.argus.financials.swing.SwingUtil;
import com.argus.financials.ui.AbstractPanel;
import com.argus.format.LimitedPlainDocument;
import com.argus.util.ReferenceCode;

public class ModelSelectionView extends AbstractPanel {

    public static final int CANCEL_OPTION = javax.swing.JOptionPane.CANCEL_OPTION;

    public static final int OK_OPTION = javax.swing.JOptionPane.OK_OPTION;

    private static ModelSelectionView view;

    private int result; // CANCEL_OPTION, OK_OPTION

    /** Creates new form ModelSelectionView */
    public ModelSelectionView() {
        initComponents();
        initComponents2();
    }

    public static boolean exists() {
        return view != null;
    }

    public static ModelSelectionView getInstance() {
        if (view == null)
            view = new ModelSelectionView();
        return view;
    }

    public String getDefaultTitle() {
        return "Selection Dialog";
    }

    private void initComponents2() {
        jTextFieldItemName.setDocument(new LimitedPlainDocument(64));

        jTextFieldItemName.getDocument().addDocumentListener(
                new javax.swing.event.DocumentListener() {
                    public void removeUpdate(
                            javax.swing.event.DocumentEvent documentEvent) {
                        // System.out.println( "removeUpdate: " );
                        jButtonOK.setEnabled(documentEvent.getDocument()
                                .getLength() > 0);
                    }

                    public void insertUpdate(
                            javax.swing.event.DocumentEvent documentEvent) {
                        // System.out.println( "insertUpdate: " );
                        jButtonOK.setEnabled(documentEvent.getDocument()
                                .getLength() > 0);
                    }

                    public void changedUpdate(
                            javax.swing.event.DocumentEvent documentEvent) {
                        // System.out.println( "changedUpdate: " );
                        // we won't ever get this with a PlainDocument
                        // Plain text components don't fire this event
                    }

                    private String getValue(javax.swing.text.Document doc)
                            throws javax.swing.text.BadLocationException {
                        return doc.getText(doc.getStartPosition().getOffset(),
                                doc.getEndPosition().getOffset());
                    }

                }

        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelSelection = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldItemName = new javax.swing.JTextField();
        jComboBoxProjections = new javax.swing.JComboBox();
        jComboBoxFinancialTypes = new javax.swing.JComboBox();
        jPanelControls = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setPreferredSize(new java.awt.Dimension(300, 185));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanelSelection.setLayout(new java.awt.GridBagLayout());

        jPanelSelection.setBorder(new javax.swing.border.EtchedBorder());
        jLabel1.setText("Item Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanelSelection.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Projections");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanelSelection.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Types");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanelSelection.add(jLabel3, gridBagConstraints);

        jTextFieldItemName.setPreferredSize(new java.awt.Dimension(250, 19));
        jTextFieldItemName.setMinimumSize(new java.awt.Dimension(250, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jPanelSelection.add(jTextFieldItemName, gridBagConstraints);

        jComboBoxProjections.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProjectionsItemStateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jPanelSelection.add(jComboBoxProjections, gridBagConstraints);

        jComboBoxFinancialTypes
                .addItemListener(new java.awt.event.ItemListener() {
                    public void itemStateChanged(java.awt.event.ItemEvent evt) {
                        jComboBoxFinancialTypesItemStateChanged(evt);
                    }
                });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jPanelSelection.add(jComboBoxFinancialTypes, gridBagConstraints);

        add(jPanelSelection);

        jButtonOK.setText("OK");
        jButtonOK.setDefaultCapable(false);
        jButtonOK.setEnabled(false);
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanelControls.add(jButtonOK);

        jButtonCancel.setText("Cancel");
        jButtonCancel.setDefaultCapable(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanelControls.add(jButtonCancel);

        add(jPanelControls);

    }// GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        result = CANCEL_OPTION;
    }// GEN-LAST:event_formComponentShown

    private void jComboBoxProjectionsItemStateChanged(
            java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBoxProjectionsItemStateChanged
        // jComboBoxFinancialTypes.setSelectedItem( ReferenceCode.CODE_NONE );
        // JComboBox cb = (JComboBox) evt.getSource();
        // if ( !SwingUtils.isFocusOwner(cb) ) return;

        Object item = evt.getItem();
        jTextFieldItemName.setText(item.toString());
        jButtonOK.setEnabled(item != ReferenceCode.CODE_NONE);
    }// GEN-LAST:event_jComboBoxProjectionsItemStateChanged

    private void jComboBoxFinancialTypesItemStateChanged(
            java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jComboBoxFinancialTypesItemStateChanged
        // jComboBoxProjections.setSelectedItem( ReferenceCode.CODE_NONE );
        // JComboBox cb = (JComboBox) evt.getSource();
        // if ( !SwingUtils.isFocusOwner(cb) ) return;

        Object item = evt.getItem();
        jTextFieldItemName.setText(item.toString());
        jButtonOK.setEnabled(item != ReferenceCode.CODE_NONE);
    }// GEN-LAST:event_jComboBoxFinancialTypesItemStateChanged

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
        SwingUtil.setVisible(this, false);
        result = CANCEL_OPTION; // by default
    }// GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOKActionPerformed
        SwingUtil.setVisible(this, false);
        result = OK_OPTION;
    }// GEN-LAST:event_jButtonOKActionPerformed

    public static ModelSelectionView display(Strategy strategy) {

        boolean exists = exists();

        ModelSelectionView view = getInstance();
        if (!exists)
            SwingUtil.add2Dialog(null, view.getDefaultTitle(), true, view,
                    false);

        try {
            view.updateView(strategy);
        } catch (com.argus.financials.api.ServiceException e) {
            e.printStackTrace(System.err);
        }

        SwingUtil.pack(view);
        SwingUtil.setVisible(view, true); // modal

        return view;

    }

    private void close() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;

    private javax.swing.JPanel jPanelSelection;

    private javax.swing.JPanel jPanelControls;

    private javax.swing.JButton jButtonOK;

    private javax.swing.JComboBox jComboBoxFinancialTypes;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JComboBox jComboBoxProjections;

    private javax.swing.JTextField jTextFieldItemName;

    // End of variables declaration//GEN-END:variables

    public int getResult() {
        return result;
    }

    public Object getItem() {
        int codeID = 0; // unknown new model
        String codeDesc = jTextFieldItemName.getText(); // never null

        Object item = jComboBoxFinancialTypes.getSelectedItem(); // ReferenceCode
        if (item != null && codeDesc.equals(item.toString()))
            return item;

        item = jComboBoxProjections.getSelectedItem(); // Model
        if (item != null && codeDesc.equals(item.toString()))
            return item;

        return new ReferenceCode(codeID, codeDesc);

    }

    public void updateView(Strategy strategy) throws com.argus.financials.api.ServiceException {
        if (strategy == null)
            return;

        PersonService person = clientService;
        if (person == null)
            return;

        Vector items = Strategy.getAllModels(person); // Model(s)
        if (items != null) {
            items.add(0, ReferenceCode.CODE_NONE); // VSH ???
            jComboBoxProjections.setModel(new javax.swing.DefaultComboBoxModel(
                    items));
        }

        Object[] items2 = financialService.findFinancialTypes(strategy.getStrategyTypeID());
        if (items2 != null) {
            // items.add( 0, ReferenceCode.CODE_NONE ); // already there
            jComboBoxFinancialTypes
                    .setModel(new javax.swing.DefaultComboBoxModel(items2));
        }

        if (jComboBoxFinancialTypes.getItemCount() > 0)
            jComboBoxFinancialTypes.setSelectedIndex(0);
        if (jComboBoxProjections.getItemCount() > 0)
            jComboBoxProjections.setSelectedIndex(0);
        jTextFieldItemName.setText(null);

        result = CANCEL_OPTION;

    }

}
