/*
 * CommentView.java
 *
 * Created on 13 November 2001, 12:36
 */

package com.argus.financials.ui.etc;

/**
 * 
 * 
 * 
 * @author valeri chibaev
 */

import com.argus.financials.etc.Comment;
import com.argus.financials.service.ServiceLocator;
import com.argus.financials.swing.SwingUtil;

public class CommentView extends javax.swing.JComponent {

    private Integer linkObjectTypeID;

    private Comment comment;

    /** Creates new form CommentView */
    public CommentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBorder(new javax.swing.border.TitledBorder("Comment"));
        jTextArea.setLineWrap(true);
        jTextArea.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane.setViewportView(jTextArea);

        add(jScrollPane);

    }

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane;

    private javax.swing.JTextArea jTextArea;

    // End of variables declaration

    /**
     * Viewable interface
     */
    public Integer getObjectType() {
        return Comment.OBJECT_TYPE_ID;
    }

    public void updateView(com.argus.financials.service.PersonService person)
            throws com.argus.financials.service.ServiceException {
        if (person == null)
            person = ServiceLocator.getInstance().getClientPerson();

        comment = person.getComment(linkObjectTypeID);
        if (comment == null)
            clearView();
        else
            jTextArea.setText(comment.getCommentText());
    }

    public void saveView(com.argus.financials.service.PersonService person)
            throws com.argus.financials.service.ServiceException,
            com.argus.financials.code.InvalidCodeException {
        if (person == null)
            person = ServiceLocator.getInstance().getClientPerson();

        if (comment == null) {
            comment = person.getComment(linkObjectTypeID);
            if (comment == null)
                comment = new Comment(ServiceLocator.getInstance()
                        .getClientPersonID());
        }

        comment.setCommentText(jTextArea.getText());

        person.setComment(linkObjectTypeID, comment);

        // this is not a independent view (will be conained in another view all
        // the time)
        // person.save();
    }

    public void clearView() {
        SwingUtil.clear(this);
        // jTextArea.setText( null );
    }

    public Object getObject() {
        return comment;
    }

    public void setObject(Object value) {
        comment = (Comment) value;
    }

    /**
     * get/set
     */
    public Integer getLinkObjectTypeID() {
        return linkObjectTypeID;
    }

    public void setLinkObjectTypeID(Integer value) {
        linkObjectTypeID = value;
    }

}
