/*
 * APProjection.java
 *
 * Created on 6 September 2002, 20:35
 */

package com.argus.financials.ui.projection;

/**
 * 
 * @author shibaevv
 */

import java.awt.Cursor;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

import com.argus.financials.chart.APGraphViewNew;
import com.argus.financials.projection.AllocatedPensionCalcNew;
import com.argus.financials.swing.SwingUtil;
import com.argus.format.Currency;
import com.argus.format.CurrencyLabelGenerator;
import com.argus.swing.SwingUtils;

public class APProjectionView extends javax.swing.JPanel {

    private APGraphViewNew graphView;

    private AllocatedPensionCalcNew apCalc;

    /** Creates new form APProjection */
    public APProjectionView(AllocatedPensionCalcNew calc) {
        apCalc = calc;
        apCalc.getSize();
        apCalc.calculate();

        initComponents();
        initComponents2();
        setDetailedTableModel(jTableData);
        initDetailedTable();
    }

    public void initComponents2() {
        graphView = new APGraphViewNew();
        graphView.setTitleAxisY1("$");
        graphView.setLabelGeneratorAxisY1(CurrencyLabelGenerator.getInstance());
        SwingUtils.setDefaultFont(graphView);
        updateChart();
        jPanel4.add(graphView);
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 1000));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4,
                javax.swing.BoxLayout.X_AXIS));

        add(jPanel4);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 510));
        jScrollPane1
                .setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1
                .setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jTableData.setBackground(java.awt.Color.lightGray);
        jScrollPane1.setViewportView(jTableData);

        jPanel1.add(jScrollPane1);

        add(jPanel1);

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jPanel2.add(jButtonClose);

        add(jPanel2);

    }// GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCloseActionPerformed
        // Add your handling code here:
        SwingUtil.setVisible(this, false);

    }// GEN-LAST:event_jButtonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;

    private javax.swing.JTable jTableData;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel1;

    // End of variables declaration//GEN-END:variables

    /***************************************************************************
     * 
     **************************************************************************/
    private TableModel detailedTableModel;

    private Object[] detailedColumnNames = new String[] { "Age",
            "Opening Balance", "Selected Pension", "Assessable Income",
            "Rebate", "Net Pension", "Earnings", "End Balance", "Minimum",
            "Maximum", "Other", "Net Tax Payable", "Excess Rebate",
            "Medicare Levy" };

    private static final int DETAILS_COLUMN_COUNT = 14;

    private void setDetailedTableModel(JTable jTable) {

        if (detailedTableModel == null) {

            detailedTableModel = new DefaultTableModel(new Object[][] {},
                    detailedColumnNames) {

                private Class[] types = new Class[] { java.lang.Integer.class,
                        java.math.BigDecimal.class, java.math.BigDecimal.class,
                        java.math.BigDecimal.class, java.math.BigDecimal.class,
                        java.math.BigDecimal.class, java.math.BigDecimal.class,
                        java.math.BigDecimal.class, java.math.BigDecimal.class,
                        java.math.BigDecimal.class, java.math.BigDecimal.class,
                        java.math.BigDecimal.class, java.math.BigDecimal.class,
                        java.math.BigDecimal.class };

                public String getColumnName(int columnIndex) {
                    return super.getColumnName(columnIndex);
                }

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return false;
                }

            };

        }

        if (jTable.getModel() == detailedTableModel)
            return;

        // jTable.setTableHeader(null);
        jTable.setModel(detailedTableModel);

        JTableHeader th = new JTableHeader(jTable.getColumnModel());
        jTable.setTableHeader(th);
        th.setFont(SwingUtils.getDefaultFont());

    }

    private void updateChart() {

        if (apCalc == null || !apCalc.isReady())
            return;

        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            // assets
            int[] age = apCalc.getAgeArray();
            double[] assets = apCalc.getEndBalanceArray();

            // nothing changed
            if (assets == null && age == null)
                return;

            // do chart
            graphView.removeChartLabels();

            graphView
                    .addChartLabels(
                            graphView
                                    .customizeChart(
                                            new double[][] { assets },
                                            apCalc.getLabels(),
                                            new String[] { "<html>Assets <i>(end-balance)</i></html>" },
                                            new java.awt.Color[] { java.awt.Color.blue },
                                            true), Currency
                                    .getCurrencyInstance());
            // let user to go to chart

        } finally {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }

    }

    private void initDetailedTable() {
        jTableData.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < jTableData.getColumnModel().getColumnCount(); i++)
            jTableData.getColumnModel().getColumn(i).setPreferredWidth(100);

        Object[][] rowData = getDetailedRowData();

        TableModel tm = jTableData.getModel();

        if (tm instanceof DefaultTableModel) {
            if (rowData == null)
                ((DefaultTableModel) tm).setRowCount(0);
            else
                ((DefaultTableModel) tm).setDataVector(rowData,
                        detailedColumnNames);

        } else {
            System.err.println("Unhandled TableModel: " + tm);
            return;
        }

    }

    private Object[][] getDetailedRowData() {

        int[] age = apCalc.getAgeArray();
        if (age == null)
            return null;

        double[] openingBalance = apCalc.getOpeningBalanceArray();
        double[] minimum = apCalc.getMinimumArray();
        double[] maximum = apCalc.getMaximumArray();
        double[] others = apCalc.getOthersArray();
        double[] selectedPension = apCalc.getSelectedPensionArray();
        double[] assessableIncome = apCalc.getAssessableIncomeArray();
        double[] netTaxPayable = apCalc.getNetTaxPayableArray();
        double[] rebate = apCalc.getRebateArray();
        double[] excessRebate = apCalc.getExcessRebateArray();
        double[] medicareLevy = apCalc.getMedicareLevyArray();
        double[] netPension = apCalc.getNetPensionArray();
        double[] endBalance = apCalc.getEndBalanceArray();
        double[] netEarnings = apCalc.getNetEarningsArray();
        try {

            Object[][] rowData = new Object[age.length][DETAILS_COLUMN_COUNT];

            for (int i = 0; i < age.length; i++) {
                rowData[i][0] = "" + age[i];
                rowData[i][1] = Currency.getCurrencyInstance().toString(
                        openingBalance[i]);
                rowData[i][2] = Currency.getCurrencyInstance().toString(
                        selectedPension[i]);
                rowData[i][3] = Currency.getCurrencyInstance().toString(
                        assessableIncome[i]);
                rowData[i][4] = Currency.getCurrencyInstance().toString(
                        rebate[i]);
                rowData[i][5] = Currency.getCurrencyInstance().toString(
                        netPension[i]);
                rowData[i][6] = Currency.getCurrencyInstance().toString(
                        netEarnings[i]);
                rowData[i][7] = Currency.getCurrencyInstance().toString(
                        endBalance[i]);
                rowData[i][8] = Currency.getCurrencyInstance().toString(
                        minimum[i]);
                rowData[i][9] = Currency.getCurrencyInstance().toString(
                        maximum[i]);
                rowData[i][10] = Currency.getCurrencyInstance().toString(
                        others[i]);
                rowData[i][11] = Currency.getCurrencyInstance().toString(
                        netTaxPayable[i]);
                rowData[i][12] = Currency.getCurrencyInstance().toString(
                        excessRebate[i]);
                rowData[i][13] = Currency.getCurrencyInstance().toString(
                        medicareLevy[i]);

            }

            return rowData;

        } catch (Exception e) {
            e.printStackTrace(System.err);
            return null;
        }

    }

}
