/*
 * InvProperty.java
 *
 * Created on 11 January 2002, 14:53
 */

package com.argus.financials.ui.projection;

/**
 * 
 * @author kevinm
 * @author valeri chibaev
 */

import java.awt.event.FocusListener;

import com.argus.financials.config.ViewSettings;
import com.argus.financials.etc.ActionEventID;
import com.argus.financials.projection.save.Model;
import com.argus.financials.swing.SwingUtil;

public class InvPropertyView extends javax.swing.JPanel implements
        ActionEventID, javax.swing.event.ChangeListener {

    private static InvPropertyView view;

    public Integer getDefaultType() {
        return null;
    }// getModel().getTypeID(); }

    public String getDefaultTitle() {
        return null;
    }// calc.getDefaultTitle(); }

    /** Creates new form InvProperty */
    public InvPropertyView() {
        initComponents();
    }

    public static boolean exists() {
        return view != null;
    }

    public static InvPropertyView getInstance() {
        if (view == null)
            view = new InvPropertyView();
        return view;
    }

    /**
     * javax.swing.event.ChangeListener interface
     */
    public void stateChanged(javax.swing.event.ChangeEvent changeEvent) {
        // updateNonEditable();
        // updateComponents();
        // updateChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        bgInterestOnly = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelPropertyDetails = new javax.swing.JPanel();
        jPanelPurchaseDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanelInterestOnly = new javax.swing.JPanel();
        jRadioButtonInterestOnlyYES = new javax.swing.JRadioButton();
        jRadioButtonInterestOnlyNO = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jPanelIncomeExpenseDetails = new javax.swing.JPanel();
        jPanelIncomeDetails = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jPanelExpenseDetails = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jPanelProjections = new javax.swing.JPanel();
        jPanelGraph = new javax.swing.JPanel();
        jPanelCapitalIncome = new javax.swing.JPanel();
        jPanelCapitalPosition = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jPanelCashFlow = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jPanelControls = new javax.swing.JPanel();
        jPanelCloseSave = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanelPreviousNext = new javax.swing.JPanel();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setPreferredSize(new java.awt.Dimension(600, 400));
        jTabbedPane.setPreferredSize(new java.awt.Dimension(2000, 1500));
        jPanelPropertyDetails.setLayout(new javax.swing.BoxLayout(
                jPanelPropertyDetails, javax.swing.BoxLayout.X_AXIS));

        jPanelPurchaseDetails.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;

        jPanelPurchaseDetails.setBorder(new javax.swing.border.TitledBorder(
                "Purchase & Property Details"));
        jLabel1.setText("Purchase Price");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel1, gridBagConstraints1);

        jLabel2.setText("Deposit Amount");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel2, gridBagConstraints1);

        jLabel3.setText("Mortgage Amount");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel3, gridBagConstraints1);

        jLabel4.setText("Term of Invesment");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel4, gridBagConstraints1);

        jLabel5.setText("Interest Rate");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel5, gridBagConstraints1);

        jLabel6.setText("Interest Only");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel6, gridBagConstraints1);

        jLabel13.setText("Payment Fequency");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel13, gridBagConstraints1);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jTextField1, gridBagConstraints1);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jTextField2, gridBagConstraints1);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jTextField4, gridBagConstraints1);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 3;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jTextField3, gridBagConstraints1);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 4;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jTextField5, gridBagConstraints1);

        jPanelInterestOnly.setLayout(new javax.swing.BoxLayout(
                jPanelInterestOnly, javax.swing.BoxLayout.X_AXIS));

        jPanelInterestOnly.setPreferredSize(new java.awt.Dimension(120, 20));
        jRadioButtonInterestOnlyYES.setText("Yes");
        bgInterestOnly.add(jRadioButtonInterestOnlyYES);
        jRadioButtonInterestOnlyYES.setPreferredSize(new java.awt.Dimension(
                130, 20));
        jPanelInterestOnly.add(jRadioButtonInterestOnlyYES);

        jRadioButtonInterestOnlyNO.setText("No");
        bgInterestOnly.add(jRadioButtonInterestOnlyNO);
        jRadioButtonInterestOnlyNO.setPreferredSize(new java.awt.Dimension(130,
                20));
        jPanelInterestOnly.add(jRadioButtonInterestOnlyNO);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 5;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jPanelInterestOnly, gridBagConstraints1);

        jLabel14.setText("Repayment Amount");
        jLabel14.setPreferredSize(new java.awt.Dimension(115, 16));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanelPurchaseDetails.add(jLabel14, gridBagConstraints1);

        jTextField7.setEditable(false);
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 7;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jTextField7, gridBagConstraints1);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 6;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jComboBox1, gridBagConstraints1);

        jLabel21.setText("Capital Growth %");
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 8;
        gridBagConstraints1.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelPurchaseDetails.add(jLabel21, gridBagConstraints1);

        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 8;
        gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelPurchaseDetails.add(jTextField17, gridBagConstraints1);

        jPanelPropertyDetails.add(jPanelPurchaseDetails);

        jPanelIncomeExpenseDetails.setLayout(new javax.swing.BoxLayout(
                jPanelIncomeExpenseDetails, javax.swing.BoxLayout.Y_AXIS));

        jPanelIncomeDetails.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;

        jPanelIncomeDetails.setBorder(new javax.swing.border.TitledBorder(
                "Income Details"));
        jLabel7.setText("Rent Per Week");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jLabel7, gridBagConstraints2);

        jLabel8.setText("Weeks Rented p.a.");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 1;
        gridBagConstraints2.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jLabel8, gridBagConstraints2);

        jLabel9.setText("Rental Income p.a.");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jLabel9, gridBagConstraints2);

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelIncomeDetails.add(jTextField8, gridBagConstraints2);

        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 1;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelIncomeDetails.add(jTextField9, gridBagConstraints2);

        jTextField10.setEditable(false);
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelIncomeDetails.add(jTextField10, gridBagConstraints2);

        jLabel23.setText("Rental Increase %");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 3;
        gridBagConstraints2.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jLabel23, gridBagConstraints2);

        jLabel24.setText("Increase Frequency");
        jLabel24.setPreferredSize(new java.awt.Dimension(115, 16));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 4;
        gridBagConstraints2.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jLabel24, gridBagConstraints2);

        jTextField18.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 5;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jTextField18, gridBagConstraints2);

        jComboBox2.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 4;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelIncomeDetails.add(jComboBox2, gridBagConstraints2);

        jLabel32.setText("ClientView Tax Rate");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 5;
        gridBagConstraints2.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jLabel32, gridBagConstraints2);

        jTextField29.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 3;
        gridBagConstraints2.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanelIncomeDetails.add(jTextField29, gridBagConstraints2);

        jPanelIncomeExpenseDetails.add(jPanelIncomeDetails);

        jPanelExpenseDetails.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints3;

        jPanelExpenseDetails.setBorder(new javax.swing.border.TitledBorder(
                "Expense Details"));
        jLabel15.setText("Insurance p.a.");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelExpenseDetails.add(jLabel15, gridBagConstraints3);

        jLabel16.setText("Water Rates p.a.");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 1;
        gridBagConstraints3.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelExpenseDetails.add(jLabel16, gridBagConstraints3);

        jLabel17.setText("Council Rates p.a.");
        jLabel17.setPreferredSize(new java.awt.Dimension(115, 16));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 2;
        gridBagConstraints3.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelExpenseDetails.add(jLabel17, gridBagConstraints3);

        jLabel18.setText("Management p.a.");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 3;
        gridBagConstraints3.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelExpenseDetails.add(jLabel18, gridBagConstraints3);

        jLabel19.setText("Maintenance p.a.");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 4;
        gridBagConstraints3.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelExpenseDetails.add(jLabel19, gridBagConstraints3);

        jLabel20.setText("Other p.a.");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 5;
        gridBagConstraints3.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanelExpenseDetails.add(jLabel20, gridBagConstraints3);

        jTextField11.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelExpenseDetails.add(jTextField11, gridBagConstraints3);

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 1;
        gridBagConstraints3.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelExpenseDetails.add(jTextField12, gridBagConstraints3);

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 2;
        gridBagConstraints3.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelExpenseDetails.add(jTextField13, gridBagConstraints3);

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 3;
        gridBagConstraints3.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelExpenseDetails.add(jTextField14, gridBagConstraints3);

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 4;
        gridBagConstraints3.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelExpenseDetails.add(jTextField15, gridBagConstraints3);

        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 5;
        gridBagConstraints3.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints3.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelExpenseDetails.add(jTextField16, gridBagConstraints3);

        jPanelIncomeExpenseDetails.add(jPanelExpenseDetails);

        jPanelPropertyDetails.add(jPanelIncomeExpenseDetails);

        jTabbedPane.addTab("Property Details", jPanelPropertyDetails);

        jPanelProjections.setLayout(new javax.swing.BoxLayout(
                jPanelProjections, javax.swing.BoxLayout.Y_AXIS));

        jPanelGraph.setBorder(new javax.swing.border.TitledBorder("Graph"));
        jPanelProjections.add(jPanelGraph);

        jPanelCapitalIncome.setLayout(new javax.swing.BoxLayout(
                jPanelCapitalIncome, javax.swing.BoxLayout.X_AXIS));

        jPanelCapitalPosition.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints4;

        jPanelCapitalPosition.setBorder(new javax.swing.border.TitledBorder(
                "Capital Position"));
        jLabel10.setText("Property Value");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 1;
        gridBagConstraints4.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCapitalPosition.add(jLabel10, gridBagConstraints4);

        jLabel11.setText("Capital Growth");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 2;
        gridBagConstraints4.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCapitalPosition.add(jLabel11, gridBagConstraints4);

        jLabel12.setText("Net Wealth Created");
        jLabel12.setPreferredSize(new java.awt.Dimension(115, 16));
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 4;
        gridBagConstraints4.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCapitalPosition.add(jLabel12, gridBagConstraints4);

        jLabel22.setText("Total Invested");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCapitalPosition.add(jLabel22, gridBagConstraints4);

        jTextField6.setEditable(false);
        jTextField6.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCapitalPosition.add(jTextField6, gridBagConstraints4);

        jTextField19.setEditable(false);
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 1;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCapitalPosition.add(jTextField19, gridBagConstraints4);

        jTextField20.setEditable(false);
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 2;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCapitalPosition.add(jTextField20, gridBagConstraints4);

        jTextField21.setEditable(false);
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 4;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCapitalPosition.add(jTextField21, gridBagConstraints4);

        jLabel25.setText("Mortgage Amount");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 3;
        gridBagConstraints4.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCapitalPosition.add(jLabel25, gridBagConstraints4);

        jTextField22.setEditable(false);
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 3;
        gridBagConstraints4.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints4.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCapitalPosition.add(jTextField22, gridBagConstraints4);

        jPanelCapitalIncome.add(jPanelCapitalPosition);

        jPanelCashFlow.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints5;

        jPanelCashFlow.setBorder(new javax.swing.border.TitledBorder(
                "Income & Cashflow"));
        jLabel26.setText("Investment Income");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCashFlow.add(jLabel26, gridBagConstraints5);

        jLabel27.setText("Interest Expense");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 1;
        gridBagConstraints5.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCashFlow.add(jLabel27, gridBagConstraints5);

        jLabel28.setText("Property Expenses");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 2;
        gridBagConstraints5.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCashFlow.add(jLabel28, gridBagConstraints5);

        jLabel29.setText("Net Income");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 3;
        gridBagConstraints5.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCashFlow.add(jLabel29, gridBagConstraints5);

        jLabel30.setText("Tax Payable");
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 5;
        gridBagConstraints5.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCashFlow.add(jLabel30, gridBagConstraints5);

        jLabel31.setText("Assessable Income");
        jLabel31.setPreferredSize(new java.awt.Dimension(115, 16));
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 0;
        gridBagConstraints5.gridy = 4;
        gridBagConstraints5.insets = new java.awt.Insets(0, 0, 0, 5);
        gridBagConstraints5.anchor = java.awt.GridBagConstraints.WEST;
        jPanelCashFlow.add(jLabel31, gridBagConstraints5);

        jTextField23.setEditable(false);
        jTextField23.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCashFlow.add(jTextField23, gridBagConstraints5);

        jTextField24.setEditable(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 1;
        gridBagConstraints5.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCashFlow.add(jTextField24, gridBagConstraints5);

        jTextField25.setEditable(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 2;
        gridBagConstraints5.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCashFlow.add(jTextField25, gridBagConstraints5);

        jTextField26.setEditable(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 3;
        gridBagConstraints5.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCashFlow.add(jTextField26, gridBagConstraints5);

        jTextField27.setEditable(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 4;
        gridBagConstraints5.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCashFlow.add(jTextField27, gridBagConstraints5);

        jTextField28.setEditable(false);
        gridBagConstraints5 = new java.awt.GridBagConstraints();
        gridBagConstraints5.gridx = 1;
        gridBagConstraints5.gridy = 5;
        gridBagConstraints5.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints5.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanelCashFlow.add(jTextField28, gridBagConstraints5);

        jPanelCapitalIncome.add(jPanelCashFlow);

        jPanelProjections.add(jPanelCapitalIncome);

        jTabbedPane.addTab("Projections", jPanelProjections);

        add(jTabbedPane);

        jPanelControls.setLayout(new javax.swing.BoxLayout(jPanelControls,
                javax.swing.BoxLayout.X_AXIS));

        jButtonClose.setText("Close");
        jPanelCloseSave.add(jButtonClose);

        jButtonSave.setText("Save");
        jPanelCloseSave.add(jButtonSave);

        jPanelControls.add(jPanelCloseSave);

        jButtonPrevious.setText("< Previous");
        jPanelPreviousNext.add(jButtonPrevious);

        jButtonNext.setText("Next >");
        jPanelPreviousNext.add(jButtonNext);

        jPanelControls.add(jPanelPreviousNext);

        add(jPanelControls);

    }// GEN-END:initComponents

    public static InvPropertyView display(final Model model, FocusListener[] listeners) {

        boolean exists = InvPropertyView.exists();

        InvPropertyView view = InvPropertyView.getInstance();
        if (!exists)
            SwingUtil.add2Frame(view, listeners,
                model == null ? view.getDefaultTitle() : model.getTitle(),
                ViewSettings.getInstance().getViewImage(
                view.getClass().getName()), true, true, true);

        // try { view.updateView( model ); }
        // catch (java.io.IOException e) { throw new RuntimeException(
        // e.getMessage() ); }

        SwingUtil.setVisible(view, true);

        return view;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgInterestOnly;

    private javax.swing.JTabbedPane jTabbedPane;

    private javax.swing.JPanel jPanelPropertyDetails;

    private javax.swing.JPanel jPanelPurchaseDetails;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabel6;

    private javax.swing.JLabel jLabel13;

    private javax.swing.JTextField jTextField1;

    private javax.swing.JTextField jTextField2;

    private javax.swing.JTextField jTextField4;

    private javax.swing.JTextField jTextField3;

    private javax.swing.JTextField jTextField5;

    private javax.swing.JPanel jPanelInterestOnly;

    private javax.swing.JRadioButton jRadioButtonInterestOnlyYES;

    private javax.swing.JRadioButton jRadioButtonInterestOnlyNO;

    private javax.swing.JLabel jLabel14;

    private javax.swing.JTextField jTextField7;

    private javax.swing.JComboBox jComboBox1;

    private javax.swing.JLabel jLabel21;

    private javax.swing.JTextField jTextField17;

    private javax.swing.JPanel jPanelIncomeExpenseDetails;

    private javax.swing.JPanel jPanelIncomeDetails;

    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JTextField jTextField8;

    private javax.swing.JTextField jTextField9;

    private javax.swing.JTextField jTextField10;

    private javax.swing.JLabel jLabel23;

    private javax.swing.JLabel jLabel24;

    private javax.swing.JTextField jTextField18;

    private javax.swing.JComboBox jComboBox2;

    private javax.swing.JLabel jLabel32;

    private javax.swing.JTextField jTextField29;

    private javax.swing.JPanel jPanelExpenseDetails;

    private javax.swing.JLabel jLabel15;

    private javax.swing.JLabel jLabel16;

    private javax.swing.JLabel jLabel17;

    private javax.swing.JLabel jLabel18;

    private javax.swing.JLabel jLabel19;

    private javax.swing.JLabel jLabel20;

    private javax.swing.JTextField jTextField11;

    private javax.swing.JTextField jTextField12;

    private javax.swing.JTextField jTextField13;

    private javax.swing.JTextField jTextField14;

    private javax.swing.JTextField jTextField15;

    private javax.swing.JTextField jTextField16;

    private javax.swing.JPanel jPanelProjections;

    private javax.swing.JPanel jPanelGraph;

    private javax.swing.JPanel jPanelCapitalIncome;

    private javax.swing.JPanel jPanelCapitalPosition;

    private javax.swing.JLabel jLabel10;

    private javax.swing.JLabel jLabel11;

    private javax.swing.JLabel jLabel12;

    private javax.swing.JLabel jLabel22;

    private javax.swing.JTextField jTextField6;

    private javax.swing.JTextField jTextField19;

    private javax.swing.JTextField jTextField20;

    private javax.swing.JTextField jTextField21;

    private javax.swing.JLabel jLabel25;

    private javax.swing.JTextField jTextField22;

    private javax.swing.JPanel jPanelCashFlow;

    private javax.swing.JLabel jLabel26;

    private javax.swing.JLabel jLabel27;

    private javax.swing.JLabel jLabel28;

    private javax.swing.JLabel jLabel29;

    private javax.swing.JLabel jLabel30;

    private javax.swing.JLabel jLabel31;

    private javax.swing.JTextField jTextField23;

    private javax.swing.JTextField jTextField24;

    private javax.swing.JTextField jTextField25;

    private javax.swing.JTextField jTextField26;

    private javax.swing.JTextField jTextField27;

    private javax.swing.JTextField jTextField28;

    private javax.swing.JPanel jPanelControls;

    private javax.swing.JPanel jPanelCloseSave;

    private javax.swing.JButton jButtonClose;

    private javax.swing.JButton jButtonSave;

    private javax.swing.JPanel jPanelPreviousNext;

    private javax.swing.JButton jButtonPrevious;

    private javax.swing.JButton jButtonNext;
    // End of variables declaration//GEN-END:variables

}
