/*
 * NonDeemedAssetsDetailsView.java
 *
 * Created on April 29, 2003, 4:35 PM
 */

package com.argus.financials.ui.projection;

import java.awt.Component;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

import com.argus.bean.AbstractComponentModel;
import com.argus.bean.BasePanel;
import com.argus.bean.FTable;
import com.argus.financials.code.FundType;
import com.argus.financials.projection.DSSCalcNew;
import com.argus.financials.projection.DocumentNames;
import com.argus.financials.projection.dss.DSSContainer;
import com.argus.financials.projection.dss.NonDeemedAssetTableModel;
import com.argus.financials.swing.SwingUtil;
import com.argus.util.ReferenceCode;

/**
 * 
 * @author shibaevv
 */
public class NonDeemedAssetsDetailsView extends BasePanel {

    public static final Object[] longValues = {
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "Annuity (Medium Term)   ", new Double(1000000000),
            new Double(1000000000), new Double(1000000000),
            new Double(1000000000) };

    private BasePanel parent;

    private AbstractComponentModel dm;

    private DSSContainer container;

    private boolean isModified;

    private FTable table;

    /** Creates new form NonDeemedAssetsDetailsView */
    public NonDeemedAssetsDetailsView(AbstractComponentModel dm,
            BasePanel parent) {
        this.dm = dm;
        this.parent = parent;
        container = ((DSSCalcNew) dm).getDSSContainer();

        addFormDataModel(dm);
        dm.addModelDataChangedListener(this);

        initComponents();
        initComponents2();
    }

    private void initComponents2() {

        table = new FTable(new NonDeemedAssetTableModel());
        table.registerComponent(DocumentNames.NON_DEEMED_ASSETS_C, parent);
        table.addFormDataChangedListener(parent);
        jScrollPane.setViewportView(table);
        jScrollPane.setNextFocusableComponent(table);
        table.setNextFocusableComponent(jButtonAdd);

        javax.swing.JComboBox cb = new javax.swing.JComboBox();
        cb.addItem(ReferenceCode.CODE_NONE);
        cb.addItem(FundType.rcANNUITY);
        cb.addItem(FundType.rcANNUITY_LONG);
        cb.addItem(FundType.rcPENSION);
        javax.swing.DefaultCellEditor ce = new javax.swing.DefaultCellEditor(cb);
        table.getColumnModel().getColumn(NonDeemedAssetTableModel.TYPE)
                .setCellEditor(ce);
        table.getColumnModel().removeColumn(
                table.getColumnModel()
                        .getColumn(NonDeemedAssetTableModel.OWNER));

        initColumnSizes(table, table.getModel());

    }

    private void initColumnSizes(JTable table, TableModel tm) {
        TableColumn column = null;
        Component comp = null;
        int headerWidth = 0;
        int cellWidth = 0;

        for (int i = 0; i < tm.getColumnCount() - 1; i++) {
            column = table.getColumnModel().getColumn(i);

            try {
                comp = table.getTableHeader().getDefaultRenderer()
                        .getTableCellRendererComponent(null,
                                column.getHeaderValue(), false, false, 0, 0);
                headerWidth = comp.getPreferredSize().width;
            } catch (NullPointerException e) {
                System.err.println("Null pointer exception!");
                System.err.println("  getHeaderRenderer returns null in 1.3.");
                System.err.println("  The replacement is getDefaultRenderer.");
            }

            comp = table.getDefaultRenderer(tm.getColumnClass(i))
                    .getTableCellRendererComponent(table, longValues[i], false,
                            false, 0, i);
            cellWidth = comp.getPreferredSize().width;

            column.setPreferredWidth(Math.max(headerWidth, cellWidth));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10,
                10, 10, 10)));
        setPreferredSize(new java.awt.Dimension(650, 300));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel1
                .setBorder(new javax.swing.border.TitledBorder("Income Streams"));
        jPanel1.add(jScrollPane);

        jButtonAdd.setText("Add");
        jButtonAdd.setPreferredSize(new java.awt.Dimension(57, 21));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jPanel4.add(jButtonAdd);

        jButtonRemove.setText("Delete");
        jButtonRemove.setPreferredSize(new java.awt.Dimension(71, 21));
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jPanel4.add(jButtonRemove);

        jPanel1.add(jPanel4);

        add(jPanel1);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanel5.add(jButtonOK);

        add(jPanel5);

    }// GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOKActionPerformed

        SwingUtil.setVisible(this, false);

    }// GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRemoveActionPerformed
        int selectedRow = table.getSelectedRow();
        if (selectedRow >= 0 && selectedRow < table.getModel().getRowCount())
            ((DefaultTableModel) table.getModel()).removeRow(selectedRow);
    }// GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAddActionPerformed
        ((NonDeemedAssetTableModel) table.getModel()).addRow();
    }// GEN-LAST:event_jButtonAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;

    private javax.swing.JScrollPane jScrollPane;

    private javax.swing.JButton jButtonOK;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JButton jButtonRemove;
    // End of variables declaration//GEN-END:variables

}
