/*
 * PAYGEtpView.java
 *
 * Created on 16 September 2002, 14:11
 */

package com.argus.financials.ui.projection;

import com.argus.bean.AbstractComponentModel;
import com.argus.financials.swing.SwingUtil;
import com.argus.financials.tax.au.ITaxConstants;

/**
 * 
 */
public class PAYGEtpViewNew extends com.argus.bean.BasePanel {

    AbstractComponentModel dm;

    /** Creates new form PAYGEtpView */
    public PAYGEtpViewNew(AbstractComponentModel dm) {

        this.dm = dm;
        addFormDataModel(dm);

        dm.addModelDataChangedListener(this);

        initComponents();

        fTextField1.addFormDataChangedListener(this);
        fTextField2.addFormDataChangedListener(this);
        fTextField3.addFormDataChangedListener(this);
        fTextField4.addFormDataChangedListener(this);
        fTextField5.addFormDataChangedListener(this);
        fTextField6.addFormDataChangedListener(this);
        fTextField7.addFormDataChangedListener(this);
        fTextField8.addFormDataChangedListener(this);
        // Add listener to LSL fields
        fComboBox1.addFormDataChangedListener(this);
        fTextField38.addFormDataChangedListener(this);
        fTextField48.addFormDataChangedListener(this);
        fTextField49.addFormDataChangedListener(this);
        fTextField50.addFormDataChangedListener(this);
        fTextField46.addFormDataChangedListener(this);
        fTextField9.addFormDataChangedListener(this);

        fTextField1.registerComponent(ITaxConstants.I_PRE_JULY_1983, this);
        fTextField2
                .registerComponent(ITaxConstants.I_POST_JUNE_1983_TAXED, this);
        fTextField3.registerComponent(ITaxConstants.I_POST_JUNE_1983_UNTAXED,
                this);
        fTextField4.registerComponent(ITaxConstants.I_UNDEDUCTED, this);
        fTextField5.registerComponent(ITaxConstants.I_CGT_EXEMPT, this);
        fTextField6.registerComponent(ITaxConstants.I_ETP_EXCESSIVE, this);
        fTextField7.registerComponent(ITaxConstants.I_CONCESSINAL, this);
        fTextField8.registerComponent(ITaxConstants.I_INVALIDITY, this);

        /**
         * Register LSL fields with datamodel change listener
         */
        fComboBox1.registerComponent(ITaxConstants.LSL_REDUNDANCY, this);
        fTextField38.registerComponent(ITaxConstants.LSL_MRT5PERCENT, this);
        fTextField48.registerComponent(ITaxConstants.LSL_CONCESSIONAL, this);
        fTextField49.registerComponent(ITaxConstants.LSL_MRT, this);
        fTextField46.registerComponent(ITaxConstants.AL_CONCESSIONAL, this);
        fTextField50.registerComponent(ITaxConstants.AL_MRT, this);
        fTextField9.registerComponent(ITaxConstants.LSL_AL_TOTAL, this);

        dm.sendNotification(new Object());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        fTextField5 = new com.argus.bean.FTextField();
        fTextField4 = new com.argus.bean.FTextField();
        fTextField7 = new com.argus.bean.FTextField();
        fTextField1 = new com.argus.bean.FTextField();
        fTextField3 = new com.argus.bean.FTextField();
        fTextField2 = new com.argus.bean.FTextField();
        fTextField8 = new com.argus.bean.FTextField();
        fTextField6 = new com.argus.bean.FTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        fComboBox1 = new com.argus.bean.FComboBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fTextField46 = new com.argus.bean.FTextField();
        fTextField50 = new com.argus.bean.FTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fTextField38 = new com.argus.bean.FTextField();
        fTextField48 = new com.argus.bean.FTextField();
        fTextField49 = new com.argus.bean.FTextField();
        jLabel12 = new javax.swing.JLabel();
        fTextField9 = new com.argus.bean.FTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(65, 350));
        setMaximumSize(new java.awt.Dimension(2147483647, 350));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
                javax.swing.BoxLayout.X_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 305));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 305));
        jPanel1.setMaximumSize(new java.awt.Dimension(65534, 305));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(10, 250));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3,
                javax.swing.BoxLayout.X_AXIS));

        jPanel3.setBorder(new javax.swing.border.TitledBorder(null,
                "ETP Components (Gross)",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Arial", 0, 11)));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 260));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 260));
        jPanel3.setMaximumSize(new java.awt.Dimension(300, 260));
        jPanel4.setLayout(new java.awt.GridLayout(9, 1));

        jPanel4.setBorder(new javax.swing.border.TitledBorder(
                new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1,
                        1)), " "));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 865));
        jPanel4.setMinimumSize(new java.awt.Dimension(180, 865));
        jPanel4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jLabel5.setText("CGT Exempt");
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel5);

        jLabel4.setText("Undeducted");
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel4);

        jLabel6.setText("Concessional");
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel6);

        jLabel1.setText("Pre 1 July 1983");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel1);

        jLabel3.setText("Post 30 June 1983 - (Untaxed)");
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel3);

        jLabel2.setText("Post 30 June 1983 - (Taxed)");
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel2);

        jLabel7.setText("Invalidity");
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel7);

        jLabel45.setText("Excess");
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel45);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(9, 0, 0, 2));

        jPanel5.setBorder(new javax.swing.border.TitledBorder(
                new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1,
                        1)), "Amount", javax.swing.border.TitledBorder.CENTER,
                javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font(
                        "Arial", 0, 11)));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 865));
        jPanel5.setMinimumSize(new java.awt.Dimension(10, 865));
        jPanel5.setMaximumSize(new java.awt.Dimension(100, 32767));
        fTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField5);

        fTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField4);

        fTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField7);

        fTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField1);

        fTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField3);

        fTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField2);

        fTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField8);

        fTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField6);

        jPanel3.add(jPanel5);

        jPanel2.add(jPanel3);

        jPanel2.add(jPanel7);

        jPanel1.add(jPanel2);

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel24.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel24.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel24.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel25.setBorder(new javax.swing.border.TitledBorder(null,
                "Long Service Leave and Annual Leave payments",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Arial", 0, 11)));
        jPanel25.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel25.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel25.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanel8.setLayout(new java.awt.GridLayout(2, 1));

        jPanel8.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 50));
        jLabel50.setText("Leave type");
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel50.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel8.add(jLabel50);

        fComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
                "Resignation/Retirement",
                "Bona fide redundancy/Invalidity/Early retirement" }));
        fComboBox1.setFont(new java.awt.Font("Arial", 0, 11));
        fComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fComboBox1ItemStateChanged(evt);
            }
        });

        jPanel8.add(fComboBox1);

        jPanel25.add(jPanel8);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6,
                javax.swing.BoxLayout.X_AXIS));

        jPanel6.setBorder(new javax.swing.border.EmptyBorder(
                new java.awt.Insets(10, 1, 1, 1)));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 230));
        jPanel6.setMinimumSize(new java.awt.Dimension(300, 220));
        jPanel6.setMaximumSize(new java.awt.Dimension(33277, 230));
        jPanel26.setLayout(new java.awt.GridLayout(10, 1));

        jPanel26.setBorder(new javax.swing.border.EmptyBorder(
                new java.awt.Insets(1, 1, 1, 10)));
        jPanel26.setPreferredSize(new java.awt.Dimension(140, 190));
        jPanel26.setMinimumSize(new java.awt.Dimension(140, 190));
        jPanel26.setMaximumSize(new java.awt.Dimension(400, 270));
        jLabel46.setText("Annual Leave :");
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel46);

        jLabel48.setText("Pre 18/08/1993");
        jLabel48
                .setToolTipText("Resignation/Retirement is default option. When selected 'No' Bona fide redundancy/Invalidity/Early retirement will be applied.");
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel48.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel48);

        jLabel64.setText("Post 18/08/1993");
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel64.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel64);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel23);

        jLabel9.setText("Long Service Leave :");
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel9);

        jLabel58.setText("Pre 15/08/1978");
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel58.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel58);

        jLabel65.setText("15/08/1978 to 18/08/1993");
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel65.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel65);

        jLabel8.setText("Post 18/08/1993");
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel8);

        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel59.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel59);

        jLabel60.setText("Total");
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel60.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel60);

        jPanel6.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout(10, 0));

        jPanel27.setBorder(new javax.swing.border.EmptyBorder(
                new java.awt.Insets(1, 1, 1, 1)));
        jPanel27.setPreferredSize(new java.awt.Dimension(85, 190));
        jPanel27.setMinimumSize(new java.awt.Dimension(85, 190));
        jPanel27.setMaximumSize(new java.awt.Dimension(108, 270));
        jLabel10.setText("Amount");
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel27.add(jLabel10);

        fTextField46.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField46);

        fTextField50.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField50);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel27.add(jLabel22);

        jLabel11.setText("Amount");
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel27.add(jLabel11);

        fTextField38.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField38);

        fTextField48.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField48);

        fTextField49.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField49);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel27.add(jLabel12);

        fTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField9);

        jPanel6.add(jPanel27);

        jPanel9.setLayout(new java.awt.GridLayout(10, 0));

        jPanel9.setBorder(new javax.swing.border.EmptyBorder(
                new java.awt.Insets(1, 10, 1, 1)));
        jPanel9.setPreferredSize(new java.awt.Dimension(70, 190));
        jPanel9.setMinimumSize(new java.awt.Dimension(70, 190));
        jLabel13.setText("Comments");
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel13);

        jLabel14.setText("All at 30 %");
        jLabel14.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel14);

        jLabel15.setText("All at MTR");
        jLabel15.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel16);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel24);

        jLabel17.setText("5% at MTR");
        jLabel17.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel17);

        jLabel18.setText("All at 30 %");
        jLabel18.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel18);

        jLabel19.setText("All at MTR");
        jLabel19.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel20);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel9.add(jLabel21);

        jPanel6.add(jPanel9);

        jPanel25.add(jPanel6);

        jPanel24.add(jPanel25);

        jPanel1.add(jPanel24);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22,
                javax.swing.BoxLayout.X_AXIS));

        jPanel23.setBorder(new javax.swing.border.EtchedBorder());
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        jPanel23.add(jButton1);

        jPanel22.add(jPanel23);

        add(jPanel22, java.awt.BorderLayout.SOUTH);

    }// GEN-END:initComponents

    private void fComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_fComboBox1ItemStateChanged
        // Add your handling code here:
        if (evt.SELECTED != evt.getStateChange())
            return;

        if (fComboBox1.getSelectedIndex() == 1) {
            fTextField50.setVisible(false);
            fTextField49.setVisible(false);
            jLabel64.setVisible(false);
            jLabel8.setVisible(false);
            jLabel15.setVisible(false);
            jLabel19.setVisible(false);
            jLabel48.setText("All Annual Leave");
            jLabel65.setText("Post 15/08/1978");

        } else {
            fTextField50.setVisible(true);
            fTextField49.setVisible(true);
            jLabel64.setVisible(true);
            jLabel8.setVisible(true);
            jLabel15.setVisible(true);
            jLabel19.setVisible(true);
            jLabel48.setText("Pre 18/08/1993");
            jLabel65.setText("15/08/1978 to 18/08/1993");

        }
    }// GEN-LAST:event_fComboBox1ItemStateChanged

    private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jOKButtonActionPerformed
        // Add your handling code here:

        SwingUtil.setVisible(this, false);

    }// GEN-LAST:event_jOKButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel6;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel45;

    private javax.swing.JPanel jPanel5;

    private com.argus.bean.FTextField fTextField5;

    private com.argus.bean.FTextField fTextField4;

    private com.argus.bean.FTextField fTextField7;

    private com.argus.bean.FTextField fTextField1;

    private com.argus.bean.FTextField fTextField3;

    private com.argus.bean.FTextField fTextField2;

    private com.argus.bean.FTextField fTextField8;

    private com.argus.bean.FTextField fTextField6;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JPanel jPanel24;

    private javax.swing.JPanel jPanel25;

    private javax.swing.JPanel jPanel8;

    private javax.swing.JLabel jLabel50;

    private com.argus.bean.FComboBox fComboBox1;

    private javax.swing.JPanel jPanel6;

    private javax.swing.JPanel jPanel26;

    private javax.swing.JLabel jLabel46;

    private javax.swing.JLabel jLabel48;

    private javax.swing.JLabel jLabel64;

    private javax.swing.JLabel jLabel23;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JLabel jLabel58;

    private javax.swing.JLabel jLabel65;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JLabel jLabel59;

    private javax.swing.JLabel jLabel60;

    private javax.swing.JPanel jPanel27;

    private javax.swing.JLabel jLabel10;

    private com.argus.bean.FTextField fTextField46;

    private com.argus.bean.FTextField fTextField50;

    private javax.swing.JLabel jLabel22;

    private javax.swing.JLabel jLabel11;

    private com.argus.bean.FTextField fTextField38;

    private com.argus.bean.FTextField fTextField48;

    private com.argus.bean.FTextField fTextField49;

    private javax.swing.JLabel jLabel12;

    private com.argus.bean.FTextField fTextField9;

    private javax.swing.JPanel jPanel9;

    private javax.swing.JLabel jLabel13;

    private javax.swing.JLabel jLabel14;

    private javax.swing.JLabel jLabel15;

    private javax.swing.JLabel jLabel16;

    private javax.swing.JLabel jLabel24;

    private javax.swing.JLabel jLabel17;

    private javax.swing.JLabel jLabel18;

    private javax.swing.JLabel jLabel19;

    private javax.swing.JLabel jLabel20;

    private javax.swing.JLabel jLabel21;

    private javax.swing.JPanel jPanel22;

    private javax.swing.JPanel jPanel23;

    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
