/*
 * PAYGEtpView.java
 *
 * Created on 16 September 2002, 14:11
 */

package com.argus.financials.ui.projection;

import com.argus.bean.AbstractComponentModel;
import com.argus.financials.swing.SwingUtil;
import com.argus.financials.tax.au.ITaxConstants;

/**
 * 
 */
public class PAYGEtpView extends com.argus.bean.BasePanel {

    AbstractComponentModel dm;

    /** Creates new form PAYGEtpView */
    public PAYGEtpView(AbstractComponentModel dm) {

        this.dm = dm;
        addFormDataModel(dm);

        dm.addModelDataChangedListener(this);

        initComponents();

        fTextField1.addFormDataChangedListener(this);
        fTextField2.addFormDataChangedListener(this);
        fTextField3.addFormDataChangedListener(this);
        fTextField4.addFormDataChangedListener(this);
        fTextField5.addFormDataChangedListener(this);
        fTextField6.addFormDataChangedListener(this);
        fTextField7.addFormDataChangedListener(this);
        fTextField8.addFormDataChangedListener(this);
        // Add listener to LSL fields
        fDateChooser1.addFormDataChangedListener(this);
        fDateChooser5.addFormDataChangedListener(this);
        fComboBox1.addFormDataChangedListener(this);
        fTextField38.addFormDataChangedListener(this);
        fTextField48.addFormDataChangedListener(this);
        fTextField49.addFormDataChangedListener(this);
        fTextField50.addFormDataChangedListener(this);
        fTextField46.addFormDataChangedListener(this);
        fCheckBox1.addFormDataChangedListener(this);

        fTextField1.registerComponent(ITaxConstants.I_PRE_JULY_1983, this);
        fTextField2
                .registerComponent(ITaxConstants.I_POST_JUNE_1983_TAXED, this);
        fTextField3.registerComponent(ITaxConstants.I_POST_JUNE_1983_UNTAXED,
                this);
        fTextField4.registerComponent(ITaxConstants.I_UNDEDUCTED, this);
        fTextField5.registerComponent(ITaxConstants.I_CGT_EXEMPT, this);
        fTextField6.registerComponent(ITaxConstants.I_ETP_EXCESSIVE, this);
        fTextField7.registerComponent(ITaxConstants.I_CONCESSINAL, this);
        fTextField8.registerComponent(ITaxConstants.I_INVALIDITY, this);

        /**
         * Register LSL fields with datamodel change listener
         */
        fDateChooser1.registerComponent(ITaxConstants.LSL_CALC_DATE, this);
        fDateChooser5.registerComponent(ITaxConstants.LSL_START_DATE, this);
        fComboBox1.registerComponent(ITaxConstants.LSL_REDUNDANCY, this);
        fTextField38.registerComponent(ITaxConstants.LSL_TOTAL_UNUSED, this);
        fTextField48.registerComponent(ITaxConstants.LSL_USED_AFTER_1978, this);
        fTextField49.registerComponent(ITaxConstants.LSL_USED_AFTER_1993, this);
        fTextField50.registerComponent(ITaxConstants.LSL_AMOUNT, this);
        fCheckBox1.registerComponent(ITaxConstants.LSL_ARE_DAYS_AVAILABLE, this);
        fTextField46.registerComponent(ITaxConstants.AL_AMOUNT, this);

        fTextField38.setVisible(false);
        fTextField48.setVisible(false);
        fTextField49.setVisible(false);

        jLabel59.setVisible(false);
        jLabel60.setVisible(false);
        jLabel61.setVisible(false);

        dm.sendNotification(new Object());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        fTextField5 = new com.argus.bean.FTextField();
        fTextField4 = new com.argus.bean.FTextField();
        fTextField7 = new com.argus.bean.FTextField();
        fTextField1 = new com.argus.bean.FTextField();
        fTextField3 = new com.argus.bean.FTextField();
        fTextField2 = new com.argus.bean.FTextField();
        fTextField8 = new com.argus.bean.FTextField();
        fTextField6 = new com.argus.bean.FTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        fDateChooser5 = new com.argus.bean.FDateChooser();
        fDateChooser1 = new com.argus.bean.FDateChooser();
        fComboBox1 = new com.argus.bean.FComboBox();
        jLabel66 = new javax.swing.JLabel();
        fTextField46 = new com.argus.bean.FTextField();
        jLabel10 = new javax.swing.JLabel();
        fTextField50 = new com.argus.bean.FTextField();
        fCheckBox1 = new com.argus.bean.FCheckBox();
        fTextField38 = new com.argus.bean.FTextField();
        fTextField48 = new com.argus.bean.FTextField();
        fTextField49 = new com.argus.bean.FTextField();
        jPanel28 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(65, 350));
        setMaximumSize(new java.awt.Dimension(2147483647, 350));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
                javax.swing.BoxLayout.X_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 300));
        jPanel1.setMaximumSize(new java.awt.Dimension(65534, 300));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(10, 250));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3,
                javax.swing.BoxLayout.X_AXIS));

        jPanel3.setBorder(new javax.swing.border.TitledBorder(null,
                "ETP Components (Gross)",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Arial", 0, 11)));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 260));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 260));
        jPanel3.setMaximumSize(new java.awt.Dimension(300, 260));
        jPanel4.setLayout(new java.awt.GridLayout(9, 1));

        jPanel4.setBorder(new javax.swing.border.TitledBorder(
                new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1,
                        1)), " "));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 865));
        jPanel4.setMinimumSize(new java.awt.Dimension(180, 865));
        jPanel4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jLabel5.setText("CGT Exempt");
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel5);

        jLabel4.setText("Undeducted");
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel4);

        jLabel6.setText("Concessional");
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel6);

        jLabel1.setText("Pre 1 July 1983");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel1);

        jLabel3.setText("Post 30 June 1983 - (Untaxed)");
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel3);

        jLabel2.setText("Post 30 June 1983 - (Taxed)");
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel2);

        jLabel7.setText("Invalidity");
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel7);

        jLabel45.setText("Excess");
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel45.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel4.add(jLabel45);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(9, 0, 0, 2));

        jPanel5.setBorder(new javax.swing.border.TitledBorder(
                new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1,
                        1)), "Amount", javax.swing.border.TitledBorder.CENTER,
                javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font(
                        "Arial", 0, 11)));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 865));
        jPanel5.setMinimumSize(new java.awt.Dimension(10, 865));
        jPanel5.setMaximumSize(new java.awt.Dimension(100, 32767));
        fTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField5);

        fTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField4);

        fTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField7);

        fTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField1);

        fTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField3);

        fTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField2);

        fTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField8);

        fTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(fTextField6);

        jPanel3.add(jPanel5);

        jPanel2.add(jPanel3);

        jPanel2.add(jPanel7);

        jPanel1.add(jPanel2);

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24,
                javax.swing.BoxLayout.Y_AXIS));

        jPanel24.setPreferredSize(new java.awt.Dimension(300, 250));
        jPanel24.setMinimumSize(new java.awt.Dimension(10, 250));
        jPanel24.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25,
                javax.swing.BoxLayout.X_AXIS));

        jPanel25.setBorder(new javax.swing.border.TitledBorder(null,
                "Long Service Leave and Annual Leave payments",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Arial", 0, 11)));
        jPanel25.setPreferredSize(new java.awt.Dimension(10, 260));
        jPanel25.setMinimumSize(new java.awt.Dimension(10, 260));
        jPanel25.setMaximumSize(new java.awt.Dimension(32767, 260));
        jPanel26.setLayout(new java.awt.GridLayout(11, 1));

        jPanel26.setBorder(new javax.swing.border.EmptyBorder(
                new java.awt.Insets(1, 1, 1, 10)));
        jPanel26.setPreferredSize(new java.awt.Dimension(160, 270));
        jPanel26.setMinimumSize(new java.awt.Dimension(160, 10));
        jPanel26.setMaximumSize(new java.awt.Dimension(400, 270));
        jLabel50.setText("Start Service Date");
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel50.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel50);

        jLabel46.setText("End Service Date");
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel46);

        jLabel48.setText("Resignation/Retirement");
        jLabel48
                .setToolTipText("Resignation/Retirement is default option. When selected 'No' Bona fide redundancy/Invalidity/Early retirement will be applied.");
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel48);

        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel64.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel64);

        jLabel9.setText("Annual Leave Amount");
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel9);

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel58.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel58);

        jLabel65.setText("LSL Amount");
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel65.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel65);

        jLabel8.setText("Manually pro-rata");
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel8);

        jLabel59.setText("Total Unused Days");
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel59.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel59);

        jLabel60.setText("Used before 18/08/1993");
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel60.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel60);

        jLabel61.setText("Used after 17/08/1993");
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel61.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel26.add(jLabel61);

        jPanel25.add(jPanel26);

        jPanel27.setLayout(new java.awt.GridLayout(11, 0));

        jPanel27.setBorder(new javax.swing.border.EmptyBorder(
                new java.awt.Insets(1, 1, 1, 1)));
        jPanel27.setPreferredSize(new java.awt.Dimension(108, 10));
        jPanel27.setMaximumSize(new java.awt.Dimension(108, 270));
        jPanel27.add(fDateChooser5);

        jPanel27.add(fDateChooser1);

        fComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
                "Yes", "No" }));
        fComboBox1.setFont(new java.awt.Font("Arial", 0, 11));
        jPanel27.add(fComboBox1);

        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel27.add(jLabel66);

        fTextField46.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField46);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel27.add(jLabel10);

        fTextField50.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField50);

        fCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EnterDaysStateChanged(evt);
            }
        });

        jPanel27.add(fCheckBox1);

        fTextField38.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField38);

        fTextField48.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField48);

        fTextField49.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel27.add(fTextField49);

        jPanel25.add(jPanel27);

        jPanel24.add(jPanel25);

        jPanel24.add(jPanel28);

        jPanel1.add(jPanel24);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22,
                javax.swing.BoxLayout.X_AXIS));

        jPanel23.setBorder(new javax.swing.border.EtchedBorder());
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        jPanel23.add(jButton1);

        jPanel22.add(jPanel23);

        add(jPanel22, java.awt.BorderLayout.SOUTH);

    }// GEN-END:initComponents

    private void EnterDaysStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_EnterDaysStateChanged
        // Add your handling code here:

        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            fTextField38.setVisible(true);
            fTextField48.setVisible(true);
            fTextField49.setVisible(true);
            jLabel59.setVisible(true);
            jLabel60.setVisible(true);
            jLabel61.setVisible(true);

        } else {
            fTextField38.setVisible(false);
            fTextField48.setVisible(false);
            fTextField49.setVisible(false);

            jLabel59.setVisible(false);
            jLabel60.setVisible(false);
            jLabel61.setVisible(false);
        }
    }// GEN-LAST:event_EnterDaysStateChanged

    private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jOKButtonActionPerformed
        // Add your handling code here:

        SwingUtil.setVisible(this, false);

    }// GEN-LAST:event_jOKButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel6;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel45;

    private javax.swing.JPanel jPanel5;

    private com.argus.bean.FTextField fTextField5;

    private com.argus.bean.FTextField fTextField4;

    private com.argus.bean.FTextField fTextField7;

    private com.argus.bean.FTextField fTextField1;

    private com.argus.bean.FTextField fTextField3;

    private com.argus.bean.FTextField fTextField2;

    private com.argus.bean.FTextField fTextField8;

    private com.argus.bean.FTextField fTextField6;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JPanel jPanel24;

    private javax.swing.JPanel jPanel25;

    private javax.swing.JPanel jPanel26;

    private javax.swing.JLabel jLabel50;

    private javax.swing.JLabel jLabel46;

    private javax.swing.JLabel jLabel48;

    private javax.swing.JLabel jLabel64;

    private javax.swing.JLabel jLabel9;

    private javax.swing.JLabel jLabel58;

    private javax.swing.JLabel jLabel65;

    private javax.swing.JLabel jLabel8;

    private javax.swing.JLabel jLabel59;

    private javax.swing.JLabel jLabel60;

    private javax.swing.JLabel jLabel61;

    private javax.swing.JPanel jPanel27;

    private com.argus.bean.FDateChooser fDateChooser5;

    private com.argus.bean.FDateChooser fDateChooser1;

    private com.argus.bean.FComboBox fComboBox1;

    private javax.swing.JLabel jLabel66;

    private com.argus.bean.FTextField fTextField46;

    private javax.swing.JLabel jLabel10;

    private com.argus.bean.FTextField fTextField50;

    private com.argus.bean.FCheckBox fCheckBox1;

    private com.argus.bean.FTextField fTextField38;

    private com.argus.bean.FTextField fTextField48;

    private com.argus.bean.FTextField fTextField49;

    private javax.swing.JPanel jPanel28;

    private javax.swing.JPanel jPanel22;

    private javax.swing.JPanel jPanel23;

    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
