/*
 * TaxResidualView.java
 *
 * Created on 9 November 2001, 16:28
 */

package com.argus.financials.ui.financials;

/**
 * 
 * @author Valeri CHIBAEV (mailto:apollosoft.net.au@gmail.com)
 */

import com.argus.format.Currency;

public class TaxResidualView extends javax.swing.JPanel {

    /** Creates new form TaxResidualView */
    public TaxResidualView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jPanel30 = new javax.swing.JPanel();
        jPanelTotalIncome = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jTextFieldTotalSalary = new javax.swing.JTextField();
        jTextFieldTotalInvestment = new javax.swing.JTextField();
        jTextFieldTotalAllowance = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jTextFieldTotalNonDiscretionary = new javax.swing.JTextField();
        jTextFieldTotalDiscretionary = new javax.swing.JTextField();
        jTextFieldTotalLiability = new javax.swing.JTextField();
        jTextFieldTotalOther = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextFieldClientTaxableIncome = new javax.swing.JTextField();
        jTextFieldPartnerTaxableIncome = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jTextField67 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel30.setLayout(new javax.swing.BoxLayout(jPanel30,
                javax.swing.BoxLayout.X_AXIS));

        jPanelTotalIncome.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;

        jPanelTotalIncome.setBorder(new javax.swing.border.TitledBorder(
                "Income"));
        jLabel61.setText("Salary/Wages");
        jLabel61.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelTotalIncome.add(jLabel61, gridBagConstraints1);

        jLabel62.setText("Investments");
        jLabel62.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        gridBagConstraints1.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelTotalIncome.add(jLabel62, gridBagConstraints1);

        jLabel63.setText("Allowance/Pension");
        jLabel63.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 2;
        gridBagConstraints1.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
        jPanelTotalIncome.add(jLabel63, gridBagConstraints1);

        jTextFieldTotalSalary.setEditable(false);
        jTextFieldTotalSalary.setBackground(java.awt.Color.lightGray);
        jTextFieldTotalSalary.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        jPanelTotalIncome.add(jTextFieldTotalSalary, gridBagConstraints1);

        jTextFieldTotalInvestment.setEditable(false);
        jTextFieldTotalInvestment.setBackground(java.awt.Color.lightGray);
        jTextFieldTotalInvestment.setPreferredSize(new java.awt.Dimension(80,
                20));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 1;
        jPanelTotalIncome.add(jTextFieldTotalInvestment, gridBagConstraints1);

        jTextFieldTotalAllowance.setEditable(false);
        jTextFieldTotalAllowance.setBackground(java.awt.Color.lightGray);
        jTextFieldTotalAllowance
                .setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 1;
        gridBagConstraints1.gridy = 2;
        jPanelTotalIncome.add(jTextFieldTotalAllowance, gridBagConstraints1);

        jPanel30.add(jPanelTotalIncome);

        jPanel33.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;

        jPanel33.setBorder(new javax.swing.border.TitledBorder("Expenses"));
        jLabel64.setText("Non-Discretionary");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanel33.add(jLabel64, gridBagConstraints2);

        jLabel65.setText("Discretionary");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 1;
        gridBagConstraints2.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanel33.add(jLabel65, gridBagConstraints2);

        jLabel66.setText("Asset/Liability");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 2;
        gridBagConstraints2.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanel33.add(jLabel66, gridBagConstraints2);

        jLabel67.setText("Other");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 0;
        gridBagConstraints2.gridy = 3;
        gridBagConstraints2.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
        jPanel33.add(jLabel67, gridBagConstraints2);

        jTextFieldTotalNonDiscretionary.setEditable(false);
        jTextFieldTotalNonDiscretionary.setBackground(java.awt.Color.lightGray);
        jTextFieldTotalNonDiscretionary
                .setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        jPanel33.add(jTextFieldTotalNonDiscretionary, gridBagConstraints2);

        jTextFieldTotalDiscretionary.setEditable(false);
        jTextFieldTotalDiscretionary.setBackground(java.awt.Color.lightGray);
        jTextFieldTotalDiscretionary.setPreferredSize(new java.awt.Dimension(
                80, 20));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 1;
        jPanel33.add(jTextFieldTotalDiscretionary, gridBagConstraints2);

        jTextFieldTotalLiability.setEditable(false);
        jTextFieldTotalLiability.setBackground(java.awt.Color.lightGray);
        jTextFieldTotalLiability
                .setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 2;
        jPanel33.add(jTextFieldTotalLiability, gridBagConstraints2);

        jTextFieldTotalOther.setEditable(false);
        jTextFieldTotalOther.setBackground(java.awt.Color.lightGray);
        jTextFieldTotalOther.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        gridBagConstraints2.gridx = 1;
        gridBagConstraints2.gridy = 3;
        jPanel33.add(jTextFieldTotalOther, gridBagConstraints2);

        jPanel30.add(jPanel33);

        add(jPanel30);

        jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31,
                javax.swing.BoxLayout.X_AXIS));

        jPanel34.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints3;

        jPanel34.setBorder(new javax.swing.border.TitledBorder("Tax"));
        jLabel68.setText("ClientView");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 0;
        jPanel34.add(jLabel68, gridBagConstraints3);

        jLabel69.setText("Taxable Income");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 1;
        gridBagConstraints3.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanel34.add(jLabel69, gridBagConstraints3);

        jLabel70.setText("Total Deductions");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 3;
        gridBagConstraints3.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanel34.add(jLabel70, gridBagConstraints3);

        jLabel71.setText("PAYG");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 5;
        gridBagConstraints3.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanel34.add(jLabel71, gridBagConstraints3);

        jLabel72.setText("Packaged Items");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 2;
        gridBagConstraints3.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanel34.add(jLabel72, gridBagConstraints3);

        jTextField62.setEditable(false);
        jTextField62.setBackground(java.awt.Color.lightGray);
        jTextField62.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 2;
        jPanel34.add(jTextField62, gridBagConstraints3);

        jTextField63.setEditable(false);
        jTextField63.setBackground(java.awt.Color.lightGray);
        jTextField63.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 5;
        jPanel34.add(jTextField63, gridBagConstraints3);

        jTextFieldClientTaxableIncome.setEditable(false);
        jTextFieldClientTaxableIncome.setBackground(java.awt.Color.lightGray);
        jTextFieldClientTaxableIncome.setPreferredSize(new java.awt.Dimension(
                80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 1;
        jPanel34.add(jTextFieldClientTaxableIncome, gridBagConstraints3);

        jTextFieldPartnerTaxableIncome.setEditable(false);
        jTextFieldPartnerTaxableIncome.setBackground(java.awt.Color.lightGray);
        jTextFieldPartnerTaxableIncome.setPreferredSize(new java.awt.Dimension(
                80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 2;
        gridBagConstraints3.gridy = 1;
        jPanel34.add(jTextFieldPartnerTaxableIncome, gridBagConstraints3);

        jTextField65.setEditable(false);
        jTextField65.setBackground(java.awt.Color.lightGray);
        jTextField65.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 4;
        jPanel34.add(jTextField65, gridBagConstraints3);

        jTextField66.setEditable(false);
        jTextField66.setBackground(java.awt.Color.lightGray);
        jTextField66.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 1;
        gridBagConstraints3.gridy = 3;
        jPanel34.add(jTextField66, gridBagConstraints3);

        jLabel73.setText("Total Rebates");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 4;
        gridBagConstraints3.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints3.anchor = java.awt.GridBagConstraints.WEST;
        jPanel34.add(jLabel73, gridBagConstraints3);

        jTextField67.setEditable(false);
        jTextField67.setBackground(java.awt.Color.lightGray);
        jTextField67.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 2;
        gridBagConstraints3.gridy = 5;
        jPanel34.add(jTextField67, gridBagConstraints3);

        jTextField69.setEditable(false);
        jTextField69.setBackground(java.awt.Color.lightGray);
        jTextField69.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 2;
        gridBagConstraints3.gridy = 2;
        jPanel34.add(jTextField69, gridBagConstraints3);

        jTextField70.setEditable(false);
        jTextField70.setBackground(java.awt.Color.lightGray);
        jTextField70.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 2;
        gridBagConstraints3.gridy = 3;
        jPanel34.add(jTextField70, gridBagConstraints3);

        jTextField71.setEditable(false);
        jTextField71.setBackground(java.awt.Color.lightGray);
        jTextField71.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 2;
        gridBagConstraints3.gridy = 4;
        jPanel34.add(jTextField71, gridBagConstraints3);

        jLabel74.setText("Partner");
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        jPanel34.add(jLabel74, gridBagConstraints3);

        jPanel31.add(jPanel34);

        jPanel35.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints4;

        jPanel35.setBorder(new javax.swing.border.TitledBorder("Net Position"));
        jLabel75.setText("Net Income");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel75, gridBagConstraints4);

        jLabel76.setText("Tax");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 1;
        gridBagConstraints4.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel76, gridBagConstraints4);

        jLabel77.setText("Expenses");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 2;
        gridBagConstraints4.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel77, gridBagConstraints4);

        jLabel78.setText("Residual");
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 0;
        gridBagConstraints4.gridy = 3;
        gridBagConstraints4.insets = new java.awt.Insets(0, 5, 0, 5);
        gridBagConstraints4.anchor = java.awt.GridBagConstraints.WEST;
        jPanel35.add(jLabel78, gridBagConstraints4);

        jTextField72.setEditable(false);
        jTextField72.setBackground(java.awt.Color.lightGray);
        jTextField72.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        jPanel35.add(jTextField72, gridBagConstraints4);

        jTextField73.setEditable(false);
        jTextField73.setBackground(java.awt.Color.lightGray);
        jTextField73.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 1;
        jPanel35.add(jTextField73, gridBagConstraints4);

        jTextField74.setEditable(false);
        jTextField74.setBackground(java.awt.Color.lightGray);
        jTextField74.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 2;
        jPanel35.add(jTextField74, gridBagConstraints4);

        jTextField75.setEditable(false);
        jTextField75.setBackground(java.awt.Color.lightGray);
        jTextField75.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints4 = new java.awt.GridBagConstraints();
        gridBagConstraints4.gridx = 1;
        gridBagConstraints4.gridy = 3;
        jPanel35.add(jTextField75, gridBagConstraints4);

        jPanel31.add(jPanel35);

        add(jPanel31);

    }// GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel30;

    private javax.swing.JPanel jPanelTotalIncome;

    private javax.swing.JLabel jLabel61;

    private javax.swing.JLabel jLabel62;

    private javax.swing.JLabel jLabel63;

    private javax.swing.JTextField jTextFieldTotalSalary;

    private javax.swing.JTextField jTextFieldTotalInvestment;

    private javax.swing.JTextField jTextFieldTotalAllowance;

    private javax.swing.JPanel jPanel33;

    private javax.swing.JLabel jLabel64;

    private javax.swing.JLabel jLabel65;

    private javax.swing.JLabel jLabel66;

    private javax.swing.JLabel jLabel67;

    private javax.swing.JTextField jTextFieldTotalNonDiscretionary;

    private javax.swing.JTextField jTextFieldTotalDiscretionary;

    private javax.swing.JTextField jTextFieldTotalLiability;

    private javax.swing.JTextField jTextFieldTotalOther;

    private javax.swing.JPanel jPanel31;

    private javax.swing.JPanel jPanel34;

    private javax.swing.JLabel jLabel68;

    private javax.swing.JLabel jLabel69;

    private javax.swing.JLabel jLabel70;

    private javax.swing.JLabel jLabel71;

    private javax.swing.JLabel jLabel72;

    private javax.swing.JTextField jTextField62;

    private javax.swing.JTextField jTextField63;

    private javax.swing.JTextField jTextFieldClientTaxableIncome;

    private javax.swing.JTextField jTextFieldPartnerTaxableIncome;

    private javax.swing.JTextField jTextField65;

    private javax.swing.JTextField jTextField66;

    private javax.swing.JLabel jLabel73;

    private javax.swing.JTextField jTextField67;

    private javax.swing.JTextField jTextField69;

    private javax.swing.JTextField jTextField70;

    private javax.swing.JTextField jTextField71;

    private javax.swing.JLabel jLabel74;

    private javax.swing.JPanel jPanel35;

    private javax.swing.JLabel jLabel75;

    private javax.swing.JLabel jLabel76;

    private javax.swing.JLabel jLabel77;

    private javax.swing.JLabel jLabel78;

    private javax.swing.JTextField jTextField72;

    private javax.swing.JTextField jTextField73;

    private javax.swing.JTextField jTextField74;

    private javax.swing.JTextField jTextField75;

    // End of variables declaration//GEN-END:variables

    public void setIncome(java.math.BigDecimal salary,
            java.math.BigDecimal investment, java.math.BigDecimal allowance) {

        jTextFieldTotalSalary.setText(Currency.getCurrencyInstance().toString(
                salary));
        jTextFieldTotalInvestment.setText(Currency.getCurrencyInstance()
                .toString(investment));
        jTextFieldTotalAllowance.setText(Currency.getCurrencyInstance()
                .toString(allowance));

    }

    public void setExpenses(java.math.BigDecimal nonDiscretionary,
            java.math.BigDecimal discretionary, java.math.BigDecimal liability,
            java.math.BigDecimal other) {

        jTextFieldTotalNonDiscretionary.setText(Currency.getCurrencyInstance()
                .toString(nonDiscretionary));
        jTextFieldTotalDiscretionary.setText(Currency.getCurrencyInstance()
                .toString(discretionary));
        jTextFieldTotalLiability.setText(Currency.getCurrencyInstance()
                .toString(liability));
        jTextFieldTotalOther.setText(Currency.getCurrencyInstance().toString(
                other));

    }

    public void setTax(java.math.BigDecimal nonDiscretionary,
            java.math.BigDecimal discretionary, java.math.BigDecimal liability,
            java.math.BigDecimal other) {

    }

    public void setNetPosition(java.math.BigDecimal nonDiscretionary,
            java.math.BigDecimal discretionary, java.math.BigDecimal liability,
            java.math.BigDecimal other) {

    }

}
