/*
 * InputDialog.java
 *
 * Created on 15 February 2002, 10:57
 */

package au.com.totemsoft.myplanner.swing;

import au.com.totemsoft.format.LimitedPlainDocument;
import au.com.totemsoft.swing.SwingUtils;

public class InputDialog extends javax.swing.JDialog {

    public static final int CANCEL_OPTION = javax.swing.JOptionPane.CANCEL_OPTION;

    public static final int OK_OPTION = javax.swing.JOptionPane.OK_OPTION;

    private static InputDialog inputDialog;

    private int result; // CANCEL_OPTION, OK_OPTION

    /** Creates new form InputDialog */
    protected InputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        SwingUtils.setDefaultFont(this);
        // SwingUtils.setDefaultColor(this);

        // ModelTitle varchar(64) NOT NULL,
        jTextFieldTitle.setDocument(new LimitedPlainDocument(64));
        // ModelDesc varchar(512),
        jTextAreaDescription.setDocument(new LimitedPlainDocument(512));

        jScrollPane.setVisible(false);

    }

    public static InputDialog getInstance() {
        if (inputDialog == null)
            inputDialog = new InputDialog(null, true);
        return inputDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        jPanelTitle = new javax.swing.JPanel();
        jTextFieldTitle = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jPanelControls = new javax.swing.JPanel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        getContentPane().setLayout(
                new javax.swing.BoxLayout(getContentPane(),
                        javax.swing.BoxLayout.Y_AXIS));

        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanelTitle.setLayout(new javax.swing.BoxLayout(jPanelTitle,
                javax.swing.BoxLayout.X_AXIS));

        jPanelTitle.setBorder(new javax.swing.border.TitledBorder("Title"));
        jTextFieldTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTitleFocusLost(evt);
            }
        });

        jPanelTitle.add(jTextFieldTitle);

        getContentPane().add(jPanelTitle);

        jScrollPane
                .setBorder(new javax.swing.border.TitledBorder("Description"));
        jScrollPane.setPreferredSize(new java.awt.Dimension(3, 1000));
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jTextAreaDescription
                .addFocusListener(new java.awt.event.FocusAdapter() {
                    public void focusLost(java.awt.event.FocusEvent evt) {
                        jTextAreaDescriptionFocusLost(evt);
                    }
                });

        jScrollPane.setViewportView(jTextAreaDescription);

        getContentPane().add(jScrollPane);

        jPanelControls.setLayout(new java.awt.FlowLayout(
                java.awt.FlowLayout.CENTER, 20, 5));

        jButtonOK.setText("OK");
        jButtonOK.setPreferredSize(new java.awt.Dimension(51, 21));
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jPanelControls.add(jButtonOK);

        jButtonCancel.setText("Cancel");
        jButtonCancel.setPreferredSize(new java.awt.Dimension(73, 21));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanelControls.add(jButtonCancel);

        getContentPane().add(jPanelControls);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
                .getScreenSize();
        setSize(new java.awt.Dimension(400, 100));
        setLocation((screenSize.width - 400) / 2, (screenSize.height - 100) / 2);
    }// GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        result = CANCEL_OPTION;
    }// GEN-LAST:event_formComponentShown

    private void jTextAreaDescriptionFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextAreaDescriptionFocusLost
        jTextAreaDescription.setText(jTextAreaDescription.getText().trim());
    }// GEN-LAST:event_jTextAreaDescriptionFocusLost

    private void jTextFieldTitleFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jTextFieldTitleFocusLost
        jTextFieldTitle.setText(jTextFieldTitle.getText().trim());
    }// GEN-LAST:event_jTextFieldTitleFocusLost

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOKActionPerformed
        hide();
        result = OK_OPTION;
    }// GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
        // jTextFieldTitle.setText( null );
        // jTextAreaDescription.setText( null );
        hide();
        // result = CANCEL_OPTION; // by default
    }// GEN-LAST:event_jButtonCancelActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }// GEN-LAST:event_closeDialog

    /**
     * @param args
     *            the command line arguments
     */
    static void main(String args[]) {
        InputDialog dlg = InputDialog.getInstance();
        // new InputDialog(new javax.swing.JFrame(), true);

        dlg.show();

        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelTitle;

    private javax.swing.JTextField jTextFieldTitle;

    private javax.swing.JScrollPane jScrollPane;

    private javax.swing.JTextArea jTextAreaDescription;

    private javax.swing.JPanel jPanelControls;

    private javax.swing.JButton jButtonOK;

    private javax.swing.JButton jButtonCancel;

    // End of variables declaration//GEN-END:variables

    public int getResult() {
        return result;
    }

    public String getSaveTitle() {
        return jTextFieldTitle.getText();
    }

    public void setSaveTitle(String input) {
        jTextFieldTitle.setText(input);
    }

    public String getSaveDescription() {
        return jTextAreaDescription.getText();
    }

    public void setSaveDescription(String input) {
        jTextAreaDescription.setText(input);
    }

}
